/**
 * Canonical Talent Bazaar name roster. One row per person: employee type, seniority,
 * gender (for authoring balance), and display name. Add mid/senior rows later; code
 * Name picks use exact seniority per role (see `getHiringNamePoolStrings`); there is no cross-tier fallback.
 * Mid- and senior-tier rows exist for all three hire roles (no tier-specific Indian skew on senior DA).
 * Interns use `campaign_manager` + `intern` (Talent Bazaar intern mode); diversity is a notch lighter than junior CM.
 *
 * Kept free of imports from `hiring.ts` to avoid circular module graphs.
 */

/** Roles that draw from this table (full roster). `hiring.ts` keeps a small legacy fallback only. */
export type HiringNameEmployeeType = "data_analyst" | "campaign_manager" | "sales_representative";

export type HiringNameSeniority = "intern" | "junior" | "mid" | "senior";

export type HiringNameRow = {
  employeeType: HiringNameEmployeeType;
  seniority: HiringNameSeniority;
  gender: "male" | "female";
  fullName: string;
  /** Talent Bazaar one-liner; when set on an intern row, hiring uses this instead of the generic intern pool. */
  hireBlurb?: string;
};

export const HIRING_NAME_ROWS: readonly HiringNameRow[] = [
  // --- Intern · campaign_manager only (40) — UI uses this role for intern hires; 20m / 20f, slightly less global mix than junior CM ---
  {
    employeeType: "campaign_manager",
    seniority: "intern",
    gender: "male",
    fullName: "Jake Morrison",
    hireBlurb:
      "Intern badge still has the plastic smell. Treats every calendar invite like a binding contract.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "intern",
    gender: "male",
    fullName: "Tyler Walsh",
    hireBlurb: "Runs on free coffee and sincere delusion that this quarter will fix the industry.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "intern",
    gender: "male",
    fullName: "Brandon Scott",
    hireBlurb:
      'Already color-coded a "crisis binder" before anyone said the words crisis binder.',
  },
  {
    employeeType: "campaign_manager",
    seniority: "intern",
    gender: "male",
    fullName: "Connor Hayes",
    hireBlurb:
      'Will ask "per my last email" in a voice that has never sent an email before today.',
  },
  {
    employeeType: "campaign_manager",
    seniority: "intern",
    gender: "male",
    fullName: "Kyle Brennan",
    hireBlurb:
      'Thinks "dress for the job you want" means lanyard plus blazer over a hoodie. Not wrong.',
  },
  {
    employeeType: "campaign_manager",
    seniority: "intern",
    gender: "male",
    fullName: "Justin Cole",
    hireBlurb:
      "Takes meeting notes titled MEETING_FINAL_v2_REAL while the meeting is still happening.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "intern",
    gender: "male",
    fullName: "Derek Nash",
    hireBlurb:
      'Owns one nice notebook they refuse to write in until something "important" happens.',
  },
  {
    employeeType: "campaign_manager",
    seniority: "intern",
    gender: "male",
    fullName: "Trevor Blake",
    hireBlurb:
      "Assumes the office printer is a moody coworker and negotiates with it politely.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "intern",
    gender: "male",
    fullName: "Lucas Finn",
    hireBlurb:
      "Joined three Slack channels, muted zero, heart-reacted to a thread about toner.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "intern",
    gender: "male",
    fullName: "Logan Marsh",
    hireBlurb:
      'Here for the reel, the resume line, and vague "exposure"—same as the rest of us, shorter contract.',
  },
  {
    employeeType: "campaign_manager",
    seniority: "intern",
    gender: "male",
    fullName: "Marcus Reid",
    hireBlurb:
      'Treats "circle back" as a full sentence and uses it like punctuation.',
  },
  {
    employeeType: "campaign_manager",
    seniority: "intern",
    gender: "male",
    fullName: "Caleb Stone",
    hireBlurb:
      "Has strong opinions on font choice for a slide deck that will never leave Draft.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "intern",
    gender: "male",
    fullName: "Nathaniel Ford",
    hireBlurb:
      'Muted the team Zoom, then unmuted to say "Sorry, was I muted?"—twice.',
  },
  {
    employeeType: "campaign_manager",
    seniority: "intern",
    gender: "male",
    fullName: "Ryan Archer",
    hireBlurb: "Keeps a LinkedIn tab open like it's a vital organ.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "intern",
    gender: "male",
    fullName: "Noah Whitaker",
    hireBlurb:
      "Intern bag: granola, gum, and one aggressively optimistic pen.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "intern",
    gender: "male",
    fullName: "Diego Ortiz",
    hireBlurb:
      "Treats the employee handbook like lore they speedrun before the all-hands.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "intern",
    gender: "male",
    fullName: "Andre Patterson",
    hireBlurb:
      'Says "No worries!" when there were, in fact, worries; everyone pretends that\'s fine.',
  },
  {
    employeeType: "campaign_manager",
    seniority: "intern",
    gender: "male",
    fullName: "Ken Yamaguchi",
    hireBlurb:
      "Labels folders ACTIONABLE, ACTIONABLEER, and FINAL_FINAL_DO_NOT_DELETE.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "intern",
    gender: "male",
    fullName: "Hassan Malik",
    hireBlurb:
      "Clocks out at 5:01 and leaves like they pulled off a heist (they answered two emails).",
  },
  {
    employeeType: "campaign_manager",
    seniority: "intern",
    gender: "male",
    fullName: "Javier Gomez",
    hireBlurb:
      "Refers to the CEO by first name after seeing them once in a hallway clip.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "intern",
    gender: "female",
    fullName: "Emma Walsh",
    hireBlurb:
      "Brought a reusable cup to signal virtue; fills it with whatever is free in the pantry.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "intern",
    gender: "female",
    fullName: "Sarah Blake",
    hireBlurb:
      'Sends "Following up!" like it\'s a legal doctrine, not a sentence.',
  },
  {
    employeeType: "campaign_manager",
    seniority: "intern",
    gender: "female",
    fullName: "Jessica Nash",
    hireBlurb:
      'Thought "FYI" meant you did something wrong; has since weaponized it neutrally.',
  },
  {
    employeeType: "campaign_manager",
    seniority: "intern",
    gender: "female",
    fullName: "Ashley Cole",
    hireBlurb:
      'Has a tab group titled Work that is 60% memes, 40% guilt.',
  },
  {
    employeeType: "campaign_manager",
    seniority: "intern",
    gender: "female",
    fullName: "Brittany Ford",
    hireBlurb:
      "Defends the broken microwave like it's office heritage.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "intern",
    gender: "female",
    fullName: "Kayla Pierce",
    hireBlurb:
      'Says "I\'ll ping you" and then disappears into the algorithm until Tuesday.',
  },
  {
    employeeType: "campaign_manager",
    seniority: "intern",
    gender: "female",
    fullName: "Morgan Tierney",
    hireBlurb:
      'Nods gravely when someone says "bandwidth" even if nobody is asking for a favor yet.',
  },
  {
    employeeType: "campaign_manager",
    seniority: "intern",
    gender: "female",
    fullName: "Sydney Archer",
    hireBlurb:
      'Calendar blocks lunch as "DO NOT BOOK" then books over it themselves once.',
  },
  {
    employeeType: "campaign_manager",
    seniority: "intern",
    gender: "female",
    fullName: "Taylor Reed",
    hireBlurb:
      'Once said "great point" three times in one meeting and meant zero of them.',
  },
  {
    employeeType: "campaign_manager",
    seniority: "intern",
    gender: "female",
    fullName: "Hailey Shaw",
    hireBlurb:
      'Still saves files to Desktop because the cloud "feels theoretical."',
  },
  {
    employeeType: "campaign_manager",
    seniority: "intern",
    gender: "female",
    fullName: "Brooke Marsh",
    hireBlurb:
      'Treats "quick sync" like a spa appointment: fifteen minutes, zero outcome.',
  },
  {
    employeeType: "campaign_manager",
    seniority: "intern",
    gender: "female",
    fullName: "Jenna Holt",
    hireBlurb: "Once apologized to a PDF out loud. Nobody asked why.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "intern",
    gender: "female",
    fullName: "Paige Turner",
    hireBlurb:
      'Adds "looping in" three people who were already in the thread, for atmosphere.',
  },
  {
    employeeType: "campaign_manager",
    seniority: "intern",
    gender: "female",
    fullName: "Rylee Cross",
    hireBlurb: 'Thinks "pivot" is a personality type, not a verb.',
  },
  {
    employeeType: "campaign_manager",
    seniority: "intern",
    gender: "female",
    fullName: "Vanessa Ortiz",
    hireBlurb:
      "Keeps one badge orientation wrong on purpose so security feels needed.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "intern",
    gender: "female",
    fullName: "Monica Reyes",
    hireBlurb:
      'Calls the shared drive "the Drive" like it is a mutual friend with drama history.',
  },
  {
    employeeType: "campaign_manager",
    seniority: "intern",
    gender: "female",
    fullName: "Aya Nakamura",
    hireBlurb:
      "Mic off, camera on, nodding like a bobblehead in a wind tunnel.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "intern",
    gender: "female",
    fullName: "Leila Farah",
    hireBlurb:
      'Color-codes urgency levels; red is "today," maroon is "today but fun."',
  },
  {
    employeeType: "campaign_manager",
    seniority: "intern",
    gender: "female",
    fullName: "Natalie Brooks",
    hireBlurb:
      'Uses "gentle reminder" the way fireworks use quiet.',
  },
  {
    employeeType: "campaign_manager",
    seniority: "intern",
    gender: "female",
    fullName: "Ines Marquez",
    hireBlurb:
      "Still thinks out-of-office is a personality trait, not a setting.",
  },

  // --- Data Analyst · junior (50) ---
  {
    employeeType: "data_analyst",
    seniority: "junior",
    gender: "male",
    fullName: "James Whitmore",
    hireBlurb: 'Calls every spreadsheet "light cleanup," then opens eight tabs and a new worldview.',
  },
  {
    employeeType: "data_analyst",
    seniority: "junior",
    gender: "male",
    fullName: "Michael O'Brien",
    hireBlurb: "Brings pivot tables to casual conversation and acts like that's normal behavior.",
  },
  {
    employeeType: "data_analyst",
    seniority: "junior",
    gender: "male",
    fullName: "Matthew Sullivan",
    hireBlurb: "Has a folder named final_final_v3_THISONE and absolute confidence in all of them.",
  },
  {
    employeeType: "data_analyst",
    seniority: "junior",
    gender: "male",
    fullName: "Ryan Cooper",
    hireBlurb: 'Says "quick data pull" the way some people say "short hike before sunset."',
  },
  {
    employeeType: "data_analyst",
    seniority: "junior",
    gender: "male",
    fullName: "David Park",
    hireBlurb: "Owns three highlighters, one mechanical keyboard, and one unresolved feud with CSV formatting.",
  },
  {
    employeeType: "data_analyst",
    seniority: "junior",
    gender: "male",
    fullName: "Chris Andersen",
    hireBlurb: "Treats broken dashboards like crime scenes and asks who touched the filters last.",
  },
  {
    employeeType: "data_analyst",
    seniority: "junior",
    gender: "male",
    fullName: "Benjamin Hayes",
    hireBlurb: 'Started labeling coffee runs as "sample size expansion" and nobody has stopped him.',
  },
  {
    employeeType: "data_analyst",
    seniority: "junior",
    gender: "male",
    fullName: "Marcus Webb",
    hireBlurb: 'Can turn "we have vibes" into a chart by lunchtime and call it alignment.',
  },
  {
    employeeType: "data_analyst",
    seniority: "junior",
    gender: "male",
    fullName: "Diego Fernández",
    hireBlurb: 'Replies "interesting" to impossible requests, then quietly builds another tab.',
  },
  {
    employeeType: "data_analyst",
    seniority: "junior",
    gender: "male",
    fullName: "Amir Hassan",
    hireBlurb: "Names every dashboard like a movie sequel: Overview II, Return of the Metric, The Last Funnel.",
  },
  {
    employeeType: "data_analyst",
    seniority: "junior",
    gender: "male",
    fullName: "Kwesi Mensah",
    hireBlurb: 'He says "just one quick query," then the office lights switch to evening mode.',
  },
  {
    employeeType: "data_analyst",
    seniority: "junior",
    gender: "male",
    fullName: "Hiro Tanaka",
    hireBlurb: "Keeps renaming tabs from new to new2 like he's dodging accountability in real time.",
  },
  {
    employeeType: "data_analyst",
    seniority: "junior",
    gender: "male",
    fullName: "Vikram Patel",
    hireBlurb: 'His idea of small talk is "so what exactly is this metric trying to feel?"',
  },
  {
    employeeType: "data_analyst",
    seniority: "junior",
    gender: "male",
    fullName: "Luca Rossi",
    hireBlurb: "Brings a ruler to printouts and calls it visual QA with a straight face.",
  },
  {
    employeeType: "data_analyst",
    seniority: "junior",
    gender: "male",
    fullName: "Omar El-Sayed",
    hireBlurb: "Has three monitor backgrounds: dark mode, darker mode, and deadline.",
  },
  {
    employeeType: "data_analyst",
    seniority: "junior",
    gender: "male",
    fullName: "Javier Morales",
    hireBlurb: 'Says "I made a tiny tracker" and then unveils something with nine filters and a legend.',
  },
  {
    employeeType: "data_analyst",
    seniority: "junior",
    gender: "male",
    fullName: "Andre Thompson",
    hireBlurb: "Keeps a tote bag with snacks, sticky notes, and one dramatic pen reserved for important numbers.",
  },
  {
    employeeType: "data_analyst",
    seniority: "junior",
    gender: "male",
    fullName: "Samuel Okonkwo",
    hireBlurb: "Can make a pie chart for anything, including who keeps stealing conference-room chargers.",
  },
  {
    employeeType: "data_analyst",
    seniority: "junior",
    gender: "male",
    fullName: "Thomas Mueller",
    hireBlurb: 'Never says "confusing," says "interesting shape in the data."',
  },
  {
    employeeType: "data_analyst",
    seniority: "junior",
    gender: "male",
    fullName: "Raj Malhotra",
    hireBlurb: "Names saved views like perfume lines: Baseline, Baseline Intense, Baseline Midnight.",
  },
  {
    employeeType: "data_analyst",
    seniority: "junior",
    gender: "male",
    fullName: "Daniel Nguyen",
    hireBlurb: "Opens a dashboard, squints, and says we are close to a story here.",
  },
  {
    employeeType: "data_analyst",
    seniority: "junior",
    gender: "male",
    fullName: "Ibrahim Farah",
    hireBlurb: "Keeps one spreadsheet tab labeled maybe useful later and treats it like treasure.",
  },
  {
    employeeType: "data_analyst",
    seniority: "junior",
    gender: "male",
    fullName: "Sean McCarthy",
    hireBlurb: "Writes metric notes like thriller spoilers: engagement drops at 3:17, do not ignore.",
  },
  {
    employeeType: "data_analyst",
    seniority: "junior",
    gender: "male",
    fullName: "Priyansh Agarwal",
    hireBlurb: 'Says "give me two minutes" with the confidence of someone who means twelve.',
  },
  {
    employeeType: "data_analyst",
    seniority: "junior",
    gender: "male",
    fullName: "Ethan Brooks",
    hireBlurb: "Once alphabetized KPI names just to feel something.",
  },
  {
    employeeType: "data_analyst",
    seniority: "junior",
    gender: "female",
    fullName: "Emily Foster",
    hireBlurb: "Brings an emergency USB stick like it is a first-aid kit for PowerPoint.",
  },
  {
    employeeType: "data_analyst",
    seniority: "junior",
    gender: "female",
    fullName: "Sarah Mitchell",
    hireBlurb: "Color-codes sticky notes by panic level, then insists it is just organization.",
  },
  {
    employeeType: "data_analyst",
    seniority: "junior",
    gender: "female",
    fullName: "Hannah Becker",
    hireBlurb: "Calls every chart version one even when everyone knows it is version nine.",
  },
  {
    employeeType: "data_analyst",
    seniority: "junior",
    gender: "female",
    fullName: "Rachel Goldman",
    hireBlurb: "Says data-informed when she means please stop guessing in public.",
  },
  {
    employeeType: "data_analyst",
    seniority: "junior",
    gender: "female",
    fullName: "Kate Sullivan",
    hireBlurb: "Can turn one messy export into three clean tabs and a minor identity crisis.",
  },
  {
    employeeType: "data_analyst",
    seniority: "junior",
    gender: "female",
    fullName: "Claire Dubois",
    hireBlurb: "Treats every new column like it deserves a naming ceremony.",
  },
  {
    employeeType: "data_analyst",
    seniority: "junior",
    gender: "female",
    fullName: "Jessica Moore",
    hireBlurb: "Says she will keep this lightweight, then opens conditional formatting like a power move.",
  },
  {
    employeeType: "data_analyst",
    seniority: "junior",
    gender: "female",
    fullName: "Olivia Brennan",
    hireBlurb: "Keeps a private note titled Questions nobody asked but should have.",
  },
  {
    employeeType: "data_analyst",
    seniority: "junior",
    gender: "female",
    fullName: "Charlotte Hayes",
    hireBlurb: "Can spot a duplicate row from ten feet away and mild disappointment.",
  },
  {
    employeeType: "data_analyst",
    seniority: "junior",
    gender: "female",
    fullName: "Priya Sharma",
    hireBlurb: "Calls chart legends the subtitles of truth.",
  },
  {
    employeeType: "data_analyst",
    seniority: "junior",
    gender: "female",
    fullName: "Maria Santos",
    hireBlurb: "Starts update emails with tiny note and ends them with three attached tables.",
  },
  {
    employeeType: "data_analyst",
    seniority: "junior",
    gender: "female",
    fullName: "Yuki Nakamura",
    hireBlurb: "Has one trusted formula and three backup formulas in case feelings change.",
  },
  {
    employeeType: "data_analyst",
    seniority: "junior",
    gender: "female",
    fullName: "Fatima Al-Rashid",
    hireBlurb: "Says this is directional when the room is clearly looking for destiny.",
  },
  {
    employeeType: "data_analyst",
    seniority: "junior",
    gender: "female",
    fullName: "Zoe Campbell",
    hireBlurb: "Gave the dashboard tabs human names and now refers to them like coworkers.",
  },
  {
    employeeType: "data_analyst",
    seniority: "junior",
    gender: "female",
    fullName: "Aisha Diallo",
    hireBlurb: "Opens raw exports with the same energy people reserve for horror trailers.",
  },
  {
    employeeType: "data_analyst",
    seniority: "junior",
    gender: "female",
    fullName: "Elena Vasquez",
    hireBlurb: "Says the chart is self-explanatory, then adds a three-page appendix anyway.",
  },
  {
    employeeType: "data_analyst",
    seniority: "junior",
    gender: "female",
    fullName: "Grace O'Connell",
    hireBlurb: "Color-codes confidence intervals like mood rings for grown-ups.",
  },
  {
    employeeType: "data_analyst",
    seniority: "junior",
    gender: "female",
    fullName: "Mei Lin",
    hireBlurb: "Treats every merge conflict like a personality test she refuses to fail.",
  },
  {
    employeeType: "data_analyst",
    seniority: "junior",
    gender: "female",
    fullName: "Nia Williams",
    hireBlurb: 'Says "interesting dip" about a number that is clearly screaming.',
  },
  {
    employeeType: "data_analyst",
    seniority: "junior",
    gender: "female",
    fullName: "Sofia Andersson",
    hireBlurb: "Names files after seasons so winter_metrics feels like a lifestyle brand.",
  },
  {
    employeeType: "data_analyst",
    seniority: "junior",
    gender: "female",
    fullName: "Ananya Krishnan",
    hireBlurb: "Keeps a sticky that says sanity check and uses it like a prayer card.",
  },
  {
    employeeType: "data_analyst",
    seniority: "junior",
    gender: "female",
    fullName: "Layla Haddad",
    hireBlurb: "Opens a filter menu with the reverence other people reserve for wine lists.",
  },
  {
    employeeType: "data_analyst",
    seniority: "junior",
    gender: "female",
    fullName: "Nina Petrova",
    hireBlurb: "Says this is mostly clean while eyeing twelve hidden rows like landmines.",
  },
  {
    employeeType: "data_analyst",
    seniority: "junior",
    gender: "female",
    fullName: "Amara Okafor",
    hireBlurb: "Treats outliers like party guests: acknowledge, seat, do not let them run the room.",
  },
  {
    employeeType: "data_analyst",
    seniority: "junior",
    gender: "female",
    fullName: "Isabel Romero",
    hireBlurb: "Ends every deck with one chart that is technically optional and emotionally mandatory.",
  },

  // --- Sales Representative · junior (50) ---
  {
    employeeType: "sales_representative",
    seniority: "junior",
    gender: "male",
    fullName: "James Whitford",
    hireBlurb: "Treats every cold lead like a warm intro and every warm intro like destiny.",
  },
  {
    employeeType: "sales_representative",
    seniority: "junior",
    gender: "male",
    fullName: "Michael Brennan",
    hireBlurb: 'Can say "just checking in" with the confidence of a person holding three reminders.',
  },
  {
    employeeType: "sales_representative",
    seniority: "junior",
    gender: "male",
    fullName: "William Cross",
    hireBlurb: "Keeps a follow-up template named gentle_nudge_final_REAL_THIS_ONE.",
  },
  {
    employeeType: "sales_representative",
    seniority: "junior",
    gender: "male",
    fullName: "Christopher Dale",
    hireBlurb: 'Calls the client "my friend" after one Zoom where both cameras were off.',
  },
  {
    employeeType: "sales_representative",
    seniority: "junior",
    gender: "male",
    fullName: "Daniel Pryce",
    hireBlurb: "Has a personal KPI called replied with at least one emoji.",
  },
  {
    employeeType: "sales_representative",
    seniority: "junior",
    gender: "male",
    fullName: "Patrick Flanagan",
    hireBlurb: 'Says "quick touchpoint" and somehow turns it into a full weekly cadence.',
  },
  {
    employeeType: "sales_representative",
    seniority: "junior",
    gender: "male",
    fullName: "Gregory Holt",
    hireBlurb: 'Believes every "circle back next quarter" is a yes wearing a fake mustache.',
  },
  {
    employeeType: "sales_representative",
    seniority: "junior",
    gender: "male",
    fullName: "Kevin McAllister",
    hireBlurb: 'Keeps a notebook titled "Objections," then writes "fair point" under all of them.',
  },
  {
    employeeType: "sales_representative",
    seniority: "junior",
    gender: "male",
    fullName: "Tyler Whitman",
    hireBlurb: "Can pitch a meeting to someone who only asked for the time.",
  },
  {
    employeeType: "sales_representative",
    seniority: "junior",
    gender: "male",
    fullName: "Brandon Keane",
    hireBlurb: "Treats pipeline hygiene like spring cleaning, except the dust is all in the CRM.",
  },
  {
    employeeType: "sales_representative",
    seniority: "junior",
    gender: "male",
    fullName: "Luke Harrington",
    hireBlurb:
      "Keeps a golf anecdote in the holster for budget season, even when nobody asked about golf.",
  },
  {
    employeeType: "sales_representative",
    seniority: "junior",
    gender: "male",
    fullName: "Eric Sutton",
    hireBlurb:
      'Voice drops a half octave when someone says "circle back" and the room knows it is game time.',
  },
  {
    employeeType: "sales_representative",
    seniority: "junior",
    gender: "male",
    fullName: "Andrew Pierce",
    hireBlurb: "Has a Friday close playlist that is legally distinct from joy.",
  },
  {
    employeeType: "sales_representative",
    seniority: "junior",
    gender: "male",
    fullName: "Steven Carmichael",
    hireBlurb:
      'Calls clients "chief" once, then spends the rest of the call apologizing with eye contact.',
  },
  {
    employeeType: "sales_representative",
    seniority: "junior",
    gender: "male",
    fullName: "Jason Whitaker",
    hireBlurb:
      "Firm handshake enthusiasm set to eleven, then immediately down to five for the coffee sip.",
  },
  {
    employeeType: "sales_representative",
    seniority: "junior",
    gender: "male",
    fullName: "Alejandro Vargas",
    hireBlurb:
      "Keeps a blazer in the car for emergencies, like weddings and Zoom calls that turn into Zoom calls.",
  },
  {
    employeeType: "sales_representative",
    seniority: "junior",
    gender: "male",
    fullName: "Malik Brooks",
    hireBlurb: 'Says "just being honest" right before the sentence that needed diplomacy.',
  },
  {
    employeeType: "sales_representative",
    seniority: "junior",
    gender: "male",
    fullName: "Rajesh Iyer",
    hireBlurb: 'Refers to the pipeline as "the boys" and nobody stops him.',
  },
  {
    employeeType: "sales_representative",
    seniority: "junior",
    gender: "male",
    fullName: "Hiroshi Okada",
    hireBlurb: "Has a business card for a steakhouse he has never eaten at.",
  },
  {
    employeeType: "sales_representative",
    seniority: "junior",
    gender: "male",
    fullName: "Darius Webb",
    hireBlurb: "Ends cold calls with a handshake joke about weather and still tells the story.",
  },
  {
    employeeType: "sales_representative",
    seniority: "junior",
    gender: "male",
    fullName: "Omar Nassar",
    hireBlurb: 'Treats "I will send you a calendar" like a threat wrapped in a hug.',
  },
  {
    employeeType: "sales_representative",
    seniority: "junior",
    gender: "male",
    fullName: "Viktor Petrov",
    hireBlurb:
      "Keeps a LinkedIn voice note drafted that never gets sent, because dignity is a dial.",
  },
  {
    employeeType: "sales_representative",
    seniority: "junior",
    gender: "male",
    fullName: "Kwame Asante",
    hireBlurb: 'Says "we are aligned" when the room is still holding a fork.',
  },
  {
    employeeType: "sales_representative",
    seniority: "junior",
    gender: "male",
    fullName: "Sanjay Mehta",
    hireBlurb: 'Has a CRM field named "vibe check" and will not explain it.',
  },
  {
    employeeType: "sales_representative",
    seniority: "junior",
    gender: "male",
    fullName: "Mateo Contreras",
    hireBlurb: 'Calls conference rooms "the arena" and the coffee machine "the trainer."',
  },
  {
    employeeType: "sales_representative",
    seniority: "junior",
    gender: "female",
    fullName: "Ashley Whitmore",
    hireBlurb: 'Says "love that for us" before the number that is not loveable.',
  },
  {
    employeeType: "sales_representative",
    seniority: "junior",
    gender: "female",
    fullName: "Brittany Cole",
    hireBlurb:
      "Work bag doubles as a showroom: lipstick, mints, and one backup deck.",
  },
  {
    employeeType: "sales_representative",
    seniority: "junior",
    gender: "female",
    fullName: "Courtney Blake",
    hireBlurb:
      'Sends "just a quick nudge" with the same warmth as a tax reminder.',
  },
  {
    employeeType: "sales_representative",
    seniority: "junior",
    gender: "female",
    fullName: "Danielle Foster",
    hireBlurb:
      "Names email threads like seasons of a drama nobody auditioned for.",
  },
  {
    employeeType: "sales_representative",
    seniority: "junior",
    gender: "female",
    fullName: "Jennifer Walsh",
    hireBlurb:
      "Treats the inbox like a garden: weed, prune, send a cheerful circling back.",
  },
  {
    employeeType: "sales_representative",
    seniority: "junior",
    gender: "female",
    fullName: "Kimberly Reed",
    hireBlurb: 'Refers to the funnel as "she" and nobody knows whether that is sweet or scary.',
  },
  {
    employeeType: "sales_representative",
    seniority: "junior",
    gender: "female",
    fullName: "Lauren Thompson",
    hireBlurb:
      "Keeps a voice memo of herself saying sounds great for instant reply energy.",
  },
  {
    employeeType: "sales_representative",
    seniority: "junior",
    gender: "female",
    fullName: "Megan O'Connell",
    hireBlurb:
      'Says "totally hear you" while color-coding urgency like it is nail polish.',
  },
  {
    employeeType: "sales_representative",
    seniority: "junior",
    gender: "female",
    fullName: "Nicole Patterson",
    hireBlurb:
      "Has a signature sign-off that changes font size based on how fake the smile is.",
  },
  {
    employeeType: "sales_representative",
    seniority: "junior",
    gender: "female",
    fullName: "Stephanie Grant",
    hireBlurb:
      'Books "focus time" blocks and immediately fills them with quick syncs.',
  },
  {
    employeeType: "sales_representative",
    seniority: "junior",
    gender: "female",
    fullName: "Tiffany Brooks",
    hireBlurb: "Treats silence on a call like a negotiable deadline.",
  },
  {
    employeeType: "sales_representative",
    seniority: "junior",
    gender: "female",
    fullName: "Victoria Hayes",
    hireBlurb: 'Sends calendar holds titled "TBD but serious."',
  },
  {
    employeeType: "sales_representative",
    seniority: "junior",
    gender: "female",
    fullName: "Heather Vaughn",
    hireBlurb:
      "Keeps one pair of heels under the desk for height and drama, one pair of sneakers for fleeing.",
  },
  {
    employeeType: "sales_representative",
    seniority: "junior",
    gender: "female",
    fullName: "Samantha Blake",
    hireBlurb:
      "Names prospects after coffee orders so nobody forgets who is who.",
  },
  {
    employeeType: "sales_representative",
    seniority: "junior",
    gender: "female",
    fullName: "Madison Clark",
    hireBlurb: 'Says "no pressure" with the exact pressure of a velvet glove.',
  },
  {
    employeeType: "sales_representative",
    seniority: "junior",
    gender: "female",
    fullName: "Priya Kapoor",
    hireBlurb: "Retail roots: can upsell a stapler and still call it relationship building.",
  },
  {
    employeeType: "sales_representative",
    seniority: "junior",
    gender: "female",
    fullName: "Yuki Tanaka",
    hireBlurb: "Quiet on the call, loud in the follow-up thread—every line earns its place.",
  },
  {
    employeeType: "sales_representative",
    seniority: "junior",
    gender: "female",
    fullName: "Carmen Vega",
    hireBlurb: "Cold lists become small talk; small talk becomes calendar holds with names spelled right.",
  },
  {
    employeeType: "sales_representative",
    seniority: "junior",
    gender: "female",
    fullName: "Fatima Hassan",
    hireBlurb: "Fundraising past: every touchpoint feels cared-for, never desperate.",
  },
  {
    employeeType: "sales_representative",
    seniority: "junior",
    gender: "female",
    fullName: "Ingrid Lindberg",
    hireBlurb: "Short calls, blunt subject lines, and a personal vendetta against ghosting.",
  },
  {
    employeeType: "sales_representative",
    seniority: "junior",
    gender: "female",
    fullName: "Zara Ahmed",
    hireBlurb: "Startup pace, grown-up polish—books the meeting without sounding thirsty.",
  },
  {
    employeeType: "sales_representative",
    seniority: "junior",
    gender: "female",
    fullName: "Renee Dubois",
    hireBlurb: "Tailors the pitch by accent and appetite for small talk.",
  },
  {
    employeeType: "sales_representative",
    seniority: "junior",
    gender: "female",
    fullName: "Monique Johnson",
    hireBlurb: "Still happiest on the phone—voice memo energy, voicemail respect.",
  },
  {
    employeeType: "sales_representative",
    seniority: "junior",
    gender: "female",
    fullName: "Sofia Costa",
    hireBlurb: "Referrals and nudges: fills the week without spamming the thread.",
  },
  {
    employeeType: "sales_representative",
    seniority: "junior",
    gender: "female",
    fullName: "Elena Popov",
    hireBlurb: "Hospitality brain: greet like a host, ask like a concierge, close like last call.",
  },

  // --- Campaign Manager · junior (50) — intern hiring uses this role in UI ---
  {
    employeeType: "campaign_manager",
    seniority: "junior",
    gender: "male",
    fullName: "Nathan Cole",
    hireBlurb: "Treats the calendar like a mood board: color-coded, slightly judgmental, weirdly calming.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "junior",
    gender: "male",
    fullName: "Alex Rivera",
    hireBlurb:
      "Names campaign folders like TV seasons so nobody can pretend launch week snuck up on them.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "junior",
    gender: "male",
    fullName: "Jordan Blake",
    hireBlurb: 'Says "light coordination" and then appears with three stakeholders and one shared doc.',
  },
  {
    employeeType: "campaign_manager",
    seniority: "junior",
    gender: "male",
    fullName: "Felix Mueller",
    hireBlurb: "Runs standups like traffic control: short lights, clear lanes, zero honking.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "junior",
    gender: "male",
    fullName: "Theo Nakamura",
    hireBlurb: 'Keeps a checklist titled sanity and checks it like it owes him money.',
  },
  {
    employeeType: "campaign_manager",
    seniority: "junior",
    gender: "male",
    fullName: "Caleb Oduya",
    hireBlurb:
      'Turns "quick sync" into an agenda, a decision, and a thank-you note in the same hour.',
  },
  {
    employeeType: "campaign_manager",
    seniority: "junior",
    gender: "male",
    fullName: "Finn McGregor",
    hireBlurb: "Chases approvals with the politeness of a butler and the persistence of a weather app.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "junior",
    gender: "male",
    fullName: "Oscar Lindqvist",
    hireBlurb: "Writes briefs so tight the creative team pretends not to be impressed.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "junior",
    gender: "male",
    fullName: "Rafael Costa",
    hireBlurb: "Handles scope creep like a bouncer: smiles first, says no second.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "junior",
    gender: "male",
    fullName: "Soren Dahl",
    hireBlurb:
      'Believes every deadline is negotiable except the one labeled "client actually replied."',
  },
  {
    employeeType: "campaign_manager",
    seniority: "junior",
    gender: "male",
    fullName: "Micah Williams",
    hireBlurb:
      'Keeps a "parking lot" doc that somehow has more traffic than the actual meeting.',
  },
  {
    employeeType: "campaign_manager",
    seniority: "junior",
    gender: "male",
    fullName: "Devon Park",
    hireBlurb: 'Says "looping in" like a lifeguard and saves everyone from drowning in threads.',
  },
  {
    employeeType: "campaign_manager",
    seniority: "junior",
    gender: "male",
    fullName: "Ellis Zhang",
    hireBlurb: 'Turns "final_v2" into a naming policy and a trust exercise.',
  },
  {
    employeeType: "campaign_manager",
    seniority: "junior",
    gender: "male",
    fullName: "Hugo Bernard",
    hireBlurb: "Treats brand voice like a seatbelt: annoying until you actually need it.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "junior",
    gender: "male",
    fullName: "Ian MacLeod",
    hireBlurb: "Runs retros with the calm of someone who has seen worse launches and worse coffee.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "junior",
    gender: "male",
    fullName: "Julian Santos",
    hireBlurb: "Negotiates timelines with the charm of a cousin who always gets the aux cord.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "junior",
    gender: "male",
    fullName: "Kofi Ansah",
    hireBlurb: "Makes status updates read like headlines: short, loud, honest.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "junior",
    gender: "male",
    fullName: "Rohan Desai",
    hireBlurb: "Speaks stakeholder as a second language: jargon in, clear asks out.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "junior",
    gender: "male",
    fullName: "Stefan Vukovic",
    hireBlurb: "Brings a spreadsheet to a brainstorm and everyone still thanks him.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "junior",
    gender: "male",
    fullName: "Tomas Havel",
    hireBlurb: 'Says "ship" with the solemnity of a captain and the anxiety of a junior.',
  },
  {
    employeeType: "campaign_manager",
    seniority: "junior",
    gender: "male",
    fullName: "Xavier Moreau",
    hireBlurb:
      'Books "five minutes" knowing the room will take twenty, then blames the espresso machine.',
  },
  {
    employeeType: "campaign_manager",
    seniority: "junior",
    gender: "male",
    fullName: "Youssef Mansour",
    hireBlurb:
      'Pins a message that says read this first and still narrates it like a movie trailer.',
  },
  {
    employeeType: "campaign_manager",
    seniority: "junior",
    gender: "male",
    fullName: "Zain Rahman",
    hireBlurb: 'Names decks after moods: chaos_light, chaos_spicy, chaos_final_for_real.',
  },
  {
    employeeType: "campaign_manager",
    seniority: "junior",
    gender: "male",
    fullName: "Adrian Bloom",
    hireBlurb:
      "Treats every stakeholder map like a family tree at Thanksgiving: polite, complicated, tense.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "junior",
    gender: "male",
    fullName: "Blake Morrison",
    hireBlurb: 'Says "perfect" while adding three follow-ups that prove nothing is perfect.',
  },
  {
    employeeType: "campaign_manager",
    seniority: "junior",
    gender: "female",
    fullName: "Emma Clarke",
    hireBlurb: "Color-codes threads by vibes, not urgency, and stands by the chaos.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "junior",
    gender: "female",
    fullName: "Sophia Nguyen",
    hireBlurb: 'Sends "quick question" payloads that arrive with attachments and a sigh.',
  },
  {
    employeeType: "campaign_manager",
    seniority: "junior",
    gender: "female",
    fullName: "Mia Torres",
    hireBlurb: "Treats one-pager requests like folklore: heard of them, never seen one in the wild.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "junior",
    gender: "female",
    fullName: "Lily Hammond",
    hireBlurb: "Meeting ritual: water, agenda, one joke about the calendar, then pretending to be fine.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "junior",
    gender: "female",
    fullName: "Nora Fitzgerald",
    hireBlurb: "Writes action items like postcards: short, sunny, slightly passive-aggressive.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "junior",
    gender: "female",
    fullName: "Paige Sullivan",
    hireBlurb: "Treats the inbox like a garden: weed, prune, apologize for the metaphor.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "junior",
    gender: "female",
    fullName: "Quinn Harper",
    hireBlurb: "Names Zoom links after moods and refuses to explain chaos_blue.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "junior",
    gender: "female",
    fullName: "Ruby Okonkwo",
    hireBlurb: 'Keeps a list of who said "circle back" and treats it like a bingo card.',
  },
  {
    employeeType: "campaign_manager",
    seniority: "junior",
    gender: "female",
    fullName: "Stella Ivanova",
    hireBlurb: 'Says "let\'s align" with the drama of a season finale.',
  },
  {
    employeeType: "campaign_manager",
    seniority: "junior",
    gender: "female",
    fullName: "Tessa Yamamoto",
    hireBlurb: "Starts every update with a breath and a bullet nobody asked for.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "junior",
    gender: "female",
    fullName: "Vera Kowalski",
    hireBlurb: "Schedules buffer time for the buffer time.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "junior",
    gender: "female",
    fullName: "Willow Fraser",
    hireBlurb: 'Uses sticky notes as wallpaper and calls it "visual project management."',
  },
  {
    employeeType: "campaign_manager",
    seniority: "junior",
    gender: "female",
    fullName: "Aria Mendez",
    hireBlurb: "Ends threads with a thumbs-up that means different things in different lighting.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "junior",
    gender: "female",
    fullName: "Bianca Ricci",
    hireBlurb: "Treats lunch like a national park: fenced, sacred, occasionally on fire.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "junior",
    gender: "female",
    fullName: "Dana Al-Farsi",
    hireBlurb: 'Forwards emails with "FYI" like she is handing out polite, tiny grenades.',
  },
  {
    employeeType: "campaign_manager",
    seniority: "junior",
    gender: "female",
    fullName: "Fiona Walsh",
    hireBlurb: "Labeled the project plan gentle and still watched it grow horns.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "junior",
    gender: "female",
    fullName: "Gia Romano",
    hireBlurb: "Keeps a countdown in the chat that nobody asked for and everyone obeys.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "junior",
    gender: "female",
    fullName: "Hope Adeyemi",
    hireBlurb: 'Starts emails with "hope you are well" and means it like a small prayer.',
  },
  {
    employeeType: "campaign_manager",
    seniority: "junior",
    gender: "female",
    fullName: "Iris van Dijk",
    hireBlurb: "Uses calendar holds as modern art: blocks of color, no explanation.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "junior",
    gender: "female",
    fullName: "Jade Patterson",
    hireBlurb: "Names files after pets and pretends that is a professional taxonomy.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "junior",
    gender: "female",
    fullName: "Kara Lindstrom",
    hireBlurb: 'Says "we can revisit" like she is scheduling a reunion with a ghost.',
  },
  {
    employeeType: "campaign_manager",
    seniority: "junior",
    gender: "female",
    fullName: "Lena Schroeder",
    hireBlurb: "Starts meetings on time and ends them when the room looks sufficiently forgiven.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "junior",
    gender: "female",
    fullName: "Maya Krishnan",
    hireBlurb: 'Keeps a thread pinned called "context" and it is eighty-seven messages deep.',
  },
  {
    employeeType: "campaign_manager",
    seniority: "junior",
    gender: "female",
    fullName: "Nina Hosseini",
    hireBlurb: 'Treats "last minute" as a genre, not an emergency.',
  },
  {
    employeeType: "campaign_manager",
    seniority: "junior",
    gender: "female",
    fullName: "Piper Donovan",
    hireBlurb: "Ends every deck with a slide titled thanks and the room feels oddly guilty.",
  },

  // --- Data Analyst · mid (30) — higher share of Indian names than junior/other pools ---
  {
    employeeType: "data_analyst",
    seniority: "mid",
    gender: "male",
    fullName: "Rohan Kapoor",
    hireBlurb:
      'Owns a "starter model" that has outlasted three reorgs; still calls it a placeholder.',
  },
  {
    employeeType: "data_analyst",
    seniority: "mid",
    gender: "male",
    fullName: "Arnav Sinha",
    hireBlurb:
      'Says "I\'ll take a quick look at the handoff" and vanishes into a place where tabs have tabs.',
  },
  {
    employeeType: "data_analyst",
    seniority: "mid",
    gender: "male",
    fullName: "Vikrant Iyer",
    hireBlurb:
      "The footnote is longer than the chart; he treats that as the main character, not a bug.",
  },
  {
    employeeType: "data_analyst",
    seniority: "mid",
    gender: "male",
    fullName: "Karan Thakur",
    hireBlurb: 'Keeps a "lessons learned" doc that is mostly folklore about the warehouse.',
  },
  {
    employeeType: "data_analyst",
    seniority: "mid",
    gender: "male",
    fullName: "Siddharth Bose",
    hireBlurb: 'When someone says "quick SQL," he hears a doorbell he cannot un-hear.',
  },
  {
    employeeType: "data_analyst",
    seniority: "mid",
    gender: "male",
    fullName: "Aditya Menon",
    hireBlurb:
      "Names files stable_final_adjacent until the room accepts that stability is a mood.",
  },
  {
    employeeType: "data_analyst",
    seniority: "mid",
    gender: "male",
    fullName: "James Holloway",
    hireBlurb:
      "Still bookmarks a dashboard from the old stack; opens it like checking on a houseplant.",
  },
  {
    employeeType: "data_analyst",
    seniority: "mid",
    gender: "male",
    fullName: "Michael Tran",
    hireBlurb: 'Says "the nuance" and the room finds the dimmer switch without being asked.',
  },
  {
    employeeType: "data_analyst",
    seniority: "mid",
    gender: "male",
    fullName: "Carlos Mendez",
    hireBlurb:
      'Version history is his autobiography; he narrates it when anyone asks which number is "real."',
  },
  {
    employeeType: "data_analyst",
    seniority: "mid",
    gender: "male",
    fullName: "Omar Bakri",
    hireBlurb:
      "Calls the sync short and saves the staring-at-the-query part for when the calendar goes quiet.",
  },
  {
    employeeType: "data_analyst",
    seniority: "mid",
    gender: "male",
    fullName: "Kwame Osei",
    hireBlurb:
      'Owns the pivot everyone copies from; calls it a "shared utility" like it is not a whole personality.',
  },
  {
    employeeType: "data_analyst",
    seniority: "mid",
    gender: "male",
    fullName: "Luca Fontana",
    hireBlurb: "Explains seasonality with hand gestures that should require a permit.",
  },
  {
    employeeType: "data_analyst",
    seniority: "mid",
    gender: "male",
    fullName: "Stefan Weber",
    hireBlurb: 'Keeps a "definitions" tab that doubles as team constitution and passive-aggressive history.',
  },
  {
    employeeType: "data_analyst",
    seniority: "mid",
    gender: "male",
    fullName: "Hiro Yamane",
    hireBlurb: 'Says "small change" and the change log arrives with chapters.',
  },
  {
    employeeType: "data_analyst",
    seniority: "mid",
    gender: "male",
    fullName: "Tomas Novak",
    hireBlurb:
      'Treats "backfill" like weather: inevitable, blamed on nobody, discussed in hushed tones.',
  },
  {
    employeeType: "data_analyst",
    seniority: "mid",
    gender: "female",
    fullName: "Anika Reddy",
    hireBlurb:
      'Her "quick deck" is a greatest-hits tour of every metric that ever broke someone\'s heart.',
  },
  {
    employeeType: "data_analyst",
    seniority: "mid",
    gender: "female",
    fullName: "Priya Deshpande",
    hireBlurb:
      "Maintains a FAQ for questions nobody has asked yet; people still scroll to the bottom.",
  },
  {
    employeeType: "data_analyst",
    seniority: "mid",
    gender: "female",
    fullName: "Kavita Nambiar",
    hireBlurb: "Puts the numbers in the email and the feelings in the attachment.",
  },
  {
    employeeType: "data_analyst",
    seniority: "mid",
    gender: "female",
    fullName: "Sneha Pillai",
    hireBlurb: 'Labels a chart "directional" and the room treats it like a spoiler warning.',
  },
  {
    employeeType: "data_analyst",
    seniority: "mid",
    gender: "female",
    fullName: "Deepa Venkatesh",
    hireBlurb: 'Calls the old KPI "the previous regime" like it is historical fiction.',
  },
  {
    employeeType: "data_analyst",
    seniority: "mid",
    gender: "female",
    fullName: "Meera Krishnan",
    hireBlurb:
      "Owns a README-in-a-tab that is longer than the model and twice as dramatic.",
  },
  {
    employeeType: "data_analyst",
    seniority: "mid",
    gender: "female",
    fullName: "Emma Lindstrom",
    hireBlurb:
      "Treats daylight savings like a data incident: annual, dramatic, blamed on the calendar.",
  },
  {
    employeeType: "data_analyst",
    seniority: "mid",
    gender: "female",
    fullName: "Yuki Sato",
    hireBlurb: 'Says "minor tweak" and the change log grows a spine.',
  },
  {
    employeeType: "data_analyst",
    seniority: "mid",
    gender: "female",
    fullName: "Laura Giordano",
    hireBlurb: "Explains the funnel with pasta metaphors until the room starts ordering lunch.",
  },
  {
    employeeType: "data_analyst",
    seniority: "mid",
    gender: "female",
    fullName: "Carmen Ibanez",
    hireBlurb: "Keeps accents in column names and treats typos like uninvited guests.",
  },
  {
    employeeType: "data_analyst",
    seniority: "mid",
    gender: "female",
    fullName: "Zoe MacKenzie",
    hireBlurb:
      'Exports with "honest" in the filename and the date twice, like an alibi.',
  },
  {
    employeeType: "data_analyst",
    seniority: "mid",
    gender: "female",
    fullName: "Rachel Matsumoto",
    hireBlurb: 'Pins a "known quirks" list that reads like a family tree of ghosts.',
  },
  {
    employeeType: "data_analyst",
    seniority: "mid",
    gender: "female",
    fullName: "Olivia Peters",
    hireBlurb: 'Calls the outlier "a guest" and will not eject it without a small ceremony.',
  },
  {
    employeeType: "data_analyst",
    seniority: "mid",
    gender: "female",
    fullName: "Hannah Okafor",
    hireBlurb: 'Says "sample size" with a velvet-rope voice: friendly face, hard limit.',
  },
  {
    employeeType: "data_analyst",
    seniority: "mid",
    gender: "female",
    fullName: "Nina Hargrove",
    hireBlurb:
      'Refers to the old join as "the haunted hallway" and only takes it in daylight.',
  },

  // --- Sales Representative · mid (30) — Western : diverse ≈ 9 : 6 per gender (same as junior sales 15:10) ---
  {
    employeeType: "sales_representative",
    seniority: "mid",
    gender: "male",
    fullName: "Mark Thornton",
    hireBlurb: "Calls his territory a garden and weeds aggressively.",
  },
  {
    employeeType: "sales_representative",
    seniority: "mid",
    gender: "male",
    fullName: "Paul Jennings",
    hireBlurb: 'Says "coach\'s notes" and the team braces.',
  },
  {
    employeeType: "sales_representative",
    seniority: "mid",
    gender: "male",
    fullName: "Scott MacKenzie",
    hireBlurb: 'Keeps a whiteboard titled "reality" in quotes.',
  },
  {
    employeeType: "sales_representative",
    seniority: "mid",
    gender: "male",
    fullName: "Brian Fletcher",
    hireBlurb: "Treats maybe from a prospect like a houseplant: water, light, denial.",
  },
  {
    employeeType: "sales_representative",
    seniority: "mid",
    gender: "male",
    fullName: "Richard Lowe",
    hireBlurb: "His voicemail is three seconds of silence and somehow authority.",
  },
  {
    employeeType: "sales_representative",
    seniority: "mid",
    gender: "male",
    fullName: "Timothy Hart",
    hireBlurb: "Schedules drive-bys that are definitely calls.",
  },
  {
    employeeType: "sales_representative",
    seniority: "mid",
    gender: "male",
    fullName: "Adam Morrison",
    hireBlurb: "Refers to the pipeline as a soap opera: same cast, new cliffhangers.",
  },
  {
    employeeType: "sales_representative",
    seniority: "mid",
    gender: "male",
    fullName: "Raymond Pierce",
    hireBlurb: "Ends emails with respectfully like he is closing a gate.",
  },
  {
    employeeType: "sales_representative",
    seniority: "mid",
    gender: "male",
    fullName: "Kenneth Wade",
    hireBlurb: 'Says "I\'m not trying to sell you" and the room knows he is.',
  },
  {
    employeeType: "sales_representative",
    seniority: "mid",
    gender: "male",
    fullName: "Alejandro Cruz",
    hireBlurb: "Explains pricing with both hands like a matador.",
  },
  {
    employeeType: "sales_representative",
    seniority: "mid",
    gender: "male",
    fullName: "Hiro Nakamura",
    hireBlurb: "Pauses after objections like he is holding a bow.",
  },
  {
    employeeType: "sales_representative",
    seniority: "mid",
    gender: "male",
    fullName: "Darius Cole",
    hireBlurb: "Names follow-ups after moods: gentle_nudge_spicy.",
  },
  {
    employeeType: "sales_representative",
    seniority: "mid",
    gender: "male",
    fullName: "Viktor Kane",
    hireBlurb: "Keeps a do-not-call-before-coffee policy for himself only.",
  },
  {
    employeeType: "sales_representative",
    seniority: "mid",
    gender: "male",
    fullName: "Kwame Mensah",
    hireBlurb: "Books working lunch and works the lunch.",
  },
  {
    employeeType: "sales_representative",
    seniority: "mid",
    gender: "male",
    fullName: "Omar Farouk",
    hireBlurb: 'Says "circle back" in three tones: question, prayer, threat.',
  },
  {
    employeeType: "sales_representative",
    seniority: "mid",
    gender: "female",
    fullName: "Ashley Reid",
    hireBlurb: "Color-codes leads by chaos; hot pink is never good.",
  },
  {
    employeeType: "sales_representative",
    seniority: "mid",
    gender: "female",
    fullName: "Brittany Lane",
    hireBlurb: "Her quick touchpoint arrives with a PDF of hope.",
  },
  {
    employeeType: "sales_representative",
    seniority: "mid",
    gender: "female",
    fullName: "Courtney Wells",
    hireBlurb: "Treats voicemail like a time capsule: leave one, regret nothing.",
  },
  {
    employeeType: "sales_representative",
    seniority: "mid",
    gender: "female",
    fullName: "Danielle Price",
    hireBlurb: "Sends calendar holds titled Decision Energy.",
  },
  {
    employeeType: "sales_representative",
    seniority: "mid",
    gender: "female",
    fullName: "Jennifer Moss",
    hireBlurb: 'Says "I hear you" and then repeats you with better lighting.',
  },
  {
    employeeType: "sales_representative",
    seniority: "mid",
    gender: "female",
    fullName: "Kimberly Hart",
    hireBlurb: "Refers to the CRM as the group chat everyone denies reading.",
  },
  {
    employeeType: "sales_representative",
    seniority: "mid",
    gender: "female",
    fullName: "Lauren Briggs",
    hireBlurb: "Ends calls with I'll float that like a balloon in a storm.",
  },
  {
    employeeType: "sales_representative",
    seniority: "mid",
    gender: "female",
    fullName: "Megan Frost",
    hireBlurb: "Keeps a sticky that says breathe before Slack.",
  },
  {
    employeeType: "sales_representative",
    seniority: "mid",
    gender: "female",
    fullName: "Nicole Archer",
    hireBlurb: "Names prospects after coffee orders; oat milk means trouble.",
  },
  {
    employeeType: "sales_representative",
    seniority: "mid",
    gender: "female",
    fullName: "Priya Subramanian",
    hireBlurb: 'Says "just checking in" with the cadence of a metronome.',
  },
  {
    employeeType: "sales_representative",
    seniority: "mid",
    gender: "female",
    fullName: "Yuki Mori",
    hireBlurb: "Treats silence on Zoom like a negotiable price.",
  },
  {
    employeeType: "sales_representative",
    seniority: "mid",
    gender: "female",
    fullName: "Fatima Rahman",
    hireBlurb: "Forwards looping-in emails that feel like a hug with teeth.",
  },
  {
    employeeType: "sales_representative",
    seniority: "mid",
    gender: "female",
    fullName: "Ingrid Saastamoinen",
    hireBlurb: 'Says "low pressure" and the spreadsheet disagrees.',
  },
  {
    employeeType: "sales_representative",
    seniority: "mid",
    gender: "female",
    fullName: "Zara Malik",
    hireBlurb: "Books focus blocks and fills them with five-minute calls.",
  },
  {
    employeeType: "sales_representative",
    seniority: "mid",
    gender: "female",
    fullName: "Elena Stavros",
    hireBlurb: "Calls the deal a journey and packs Dramamine.",
  },

  // --- Campaign Manager · mid (30) — same diversity mix as junior CM (Western + global) ---
  {
    employeeType: "campaign_manager",
    seniority: "mid",
    gender: "male",
    fullName: "Leo Sanford",
    hireBlurb: "Runs a 'light touch' workflow that still pulls three approvals out of a hat.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "mid",
    gender: "male",
    fullName: "Maxwell Byrne",
    hireBlurb: "Names folders after weather and blames the forecast when things slip.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "mid",
    gender: "male",
    fullName: "Connor Walsh",
    hireBlurb: 'Says "sync" and the calendar hears a drumline.',
  },
  {
    employeeType: "campaign_manager",
    seniority: "mid",
    gender: "male",
    fullName: "Ethan Rowan",
    hireBlurb: "Tracks who said 'final' and files it under mythology.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "mid",
    gender: "male",
    fullName: "Owen Fitzgerald",
    hireBlurb: "Books a 'quick' call and brings a novella disguised as an agenda.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "mid",
    gender: "male",
    fullName: "Reid Campbell",
    hireBlurb: "Color-codes risk like traffic lights; the room still runs red anyway.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "mid",
    gender: "male",
    fullName: "Graham Hutchins",
    hireBlurb: "Keeps a 'phase 2' note that never ends; everyone pretends that is fine.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "mid",
    gender: "male",
    fullName: "Desmond Okoye",
    hireBlurb: "Treats 'next week' as a rumor that might visit the calendar.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "mid",
    gender: "male",
    fullName: "Malik Bouazza",
    hireBlurb: "Forwards FYI that lands like weather: everyone dresses wrong.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "mid",
    gender: "male",
    fullName: "Kenzo Aoki",
    hireBlurb: 'Says "minimal" and the appendix files a complaint.',
  },
  {
    employeeType: "campaign_manager",
    seniority: "mid",
    gender: "male",
    fullName: "Dante Ferreira",
    hireBlurb: "Keeps a 'single source of truth' that moves apartments every sprint.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "mid",
    gender: "male",
    fullName: "Nico Papadopoulos",
    hireBlurb: "Names milestones after constellations and denies astrology.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "mid",
    gender: "male",
    fullName: "Matteo Bernardi",
    hireBlurb: "Explains the funnel with wine metaphors until the room is tipsy on metaphors.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "mid",
    gender: "male",
    fullName: "Samir Haddad",
    hireBlurb: 'Says "low lift" and the calendar starts crying quietly.',
  },
  {
    employeeType: "campaign_manager",
    seniority: "mid",
    gender: "male",
    fullName: "Viktor Lindstrom",
    hireBlurb: "Schedules buffer time for the buffer's emotional needs.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "mid",
    gender: "female",
    fullName: "Chloe Brennan",
    hireBlurb: "Her one-pager is a novella with a table of contents.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "mid",
    gender: "female",
    fullName: "Harper Whitfield",
    hireBlurb: "Threads titled 'quick question' arrive with a zip file of context.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "mid",
    gender: "female",
    fullName: "Ivy Langford",
    hireBlurb: "Keeps a backlog of jokes about the backlog; nobody laughs, everyone nods.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "mid",
    gender: "female",
    fullName: "Julianne Meyer",
    hireBlurb: 'Says "circle back" like it is a spell with a cooldown.',
  },
  {
    employeeType: "campaign_manager",
    seniority: "mid",
    gender: "female",
    fullName: "Keira Donovan",
    hireBlurb: "Treats Slack like a stage: every emoji is blocking and intentional.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "mid",
    gender: "female",
    fullName: "Lucia Sandoval",
    hireBlurb: "Launches with a countdown and a minute of silence for the old plan.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "mid",
    gender: "female",
    fullName: "Milena Novak",
    hireBlurb: "Her status updates are director's cuts.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "mid",
    gender: "female",
    fullName: "Naomi Sutherland",
    hireBlurb: "Color-codes calendars by panic level; everyone ignores the key.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "mid",
    gender: "female",
    fullName: "Ophelia Reyes",
    hireBlurb: "Ends decks with 'questions?' and the room reconsiders speech.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "mid",
    gender: "female",
    fullName: "Penelope Shaw",
    hireBlurb: "Keeps a FAQ for chaos; it answers nothing, comforts everyone.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "mid",
    gender: "female",
    fullName: "Rowan Gillespie",
    hireBlurb: "Says alignment while moving three deadlines and blaming the solstice.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "mid",
    gender: "female",
    fullName: "Selene Park",
    hireBlurb: "Books focus time and fills it with 'urgent' syncs that are definitely not urgent.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "mid",
    gender: "female",
    fullName: "Talia Benoit",
    hireBlurb: 'Says "on-brand" like a verdict.',
  },
  {
    employeeType: "campaign_manager",
    seniority: "mid",
    gender: "female",
    fullName: "Uma Srinivasan",
    hireBlurb: "Her light recap is a trilogy with a post-credits scene.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "mid",
    gender: "female",
    fullName: "Wren Holbrook",
    hireBlurb: "Names meetings after birds; the hawk is never a good sign.",
  },

  // --- Data Analyst · senior (10) — even gender split; balanced geography, no Indian over-index ---
  {
    employeeType: "data_analyst",
    seniority: "senior",
    gender: "male",
    fullName: "Walter Brent",
    hireBlurb:
      "Opens with a slide titled historical context and the room sits straighter without knowing why.",
  },
  {
    employeeType: "data_analyst",
    seniority: "senior",
    gender: "male",
    fullName: "Lars Holm",
    hireBlurb: "Measures tenure in schema migrations and sighs like weather.",
  },
  {
    employeeType: "data_analyst",
    seniority: "senior",
    gender: "male",
    fullName: "Sergei Volkov",
    hireBlurb:
      "Calls the pipeline the old country and only visits in daylight, with witnesses.",
  },
  {
    employeeType: "data_analyst",
    seniority: "senior",
    gender: "male",
    fullName: "Enzo Marchetti",
    hireBlurb: "Explains confidence intervals with both hands like he is conducting traffic.",
  },
  {
    employeeType: "data_analyst",
    seniority: "senior",
    gender: "male",
    fullName: "Sean Tierney",
    hireBlurb: 'Says "grand" about a chart that just threatened someone.',
  },
  {
    employeeType: "data_analyst",
    seniority: "senior",
    gender: "female",
    fullName: "Moira Stack",
    hireBlurb: "Keeps a folder labeled unless legal is cc'd and treats it like a velvet rope.",
  },
  {
    employeeType: "data_analyst",
    seniority: "senior",
    gender: "female",
    fullName: "Helena Martens",
    hireBlurb: "Calls the dashboard the flagship and treats typos like mutiny.",
  },
  {
    employeeType: "data_analyst",
    seniority: "senior",
    gender: "female",
    fullName: "Renata Kovacs",
    hireBlurb:
      "Reads actionable in a brief and hears someone else will own this eventually.",
  },
  {
    employeeType: "data_analyst",
    seniority: "senior",
    gender: "female",
    fullName: "Diane Kehoe",
    hireBlurb: 'Ends every review with "for the record" like she is closing a deposition.',
  },
  {
    employeeType: "data_analyst",
    seniority: "senior",
    gender: "female",
    fullName: "Elin Svendsen",
    hireBlurb:
      "Maintains a source-of-truth doc that predates the current product name.",
  },

  // --- Sales Representative · senior (10) — even gender split ---
  {
    employeeType: "sales_representative",
    seniority: "senior",
    gender: "male",
    fullName: "Douglas Shaw",
    hireBlurb: "Brings a printed agenda to a Zoom and does not apologize.",
  },
  {
    employeeType: "sales_representative",
    seniority: "senior",
    gender: "male",
    fullName: "Philip Grant",
    hireBlurb: 'Says "let me level-set" and the room reaches for water.',
  },
  {
    employeeType: "sales_representative",
    seniority: "senior",
    gender: "male",
    fullName: "Kenji Moriwaki",
    hireBlurb: "Treats silence after a number like a season finale—holds breath, credits roll.",
  },
  {
    employeeType: "sales_representative",
    seniority: "senior",
    gender: "male",
    fullName: "Russell Tate",
    hireBlurb:
      "Names pipeline stages after seasons: winter_truth, spring_hope, Q4_denial.",
  },
  {
    employeeType: "sales_representative",
    seniority: "senior",
    gender: "male",
    fullName: "Craig Hodges",
    hireBlurb: 'Ends "circle back" the way other people say amen—everyone bows.',
  },
  {
    employeeType: "sales_representative",
    seniority: "senior",
    gender: "female",
    fullName: "Deborah Klein",
    hireBlurb:
      "OOO message is a novella; the replies still start with quick question.",
  },
  {
    employeeType: "sales_representative",
    seniority: "senior",
    gender: "female",
    fullName: "Victoria Lang",
    hireBlurb:
      "Refers to procurement as the season finale and packs snacks for the wait.",
  },
  {
    employeeType: "sales_representative",
    seniority: "senior",
    gender: "female",
    fullName: "Sandra Moss",
    hireBlurb: 'Says "relationship account" like it is a marriage older than the CRM.',
  },
  {
    employeeType: "sales_representative",
    seniority: "senior",
    gender: "female",
    fullName: "Luisa Ordonez",
    hireBlurb: "Negotiates in three languages; the apologies are the fourth.",
  },
  {
    employeeType: "sales_representative",
    seniority: "senior",
    gender: "female",
    fullName: "Janet Calder",
    hireBlurb:
      "Calls the deal the asset and treats it like a house with history and a leaky roof.",
  },

  // --- Campaign Manager · senior (10) — even gender split ---
  {
    employeeType: "campaign_manager",
    seniority: "senior",
    gender: "male",
    fullName: "Garrett Sloan",
    hireBlurb: "Calls the kickoff a coronation and brings velvet-rope energy.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "senior",
    gender: "male",
    fullName: "Mitchell Crane",
    hireBlurb: "His RACI chart has footnotes; the footnotes have footnotes.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "senior",
    gender: "male",
    fullName: "Declan Riordan",
    hireBlurb: "Says we own the narrative and the room checks who paid for the room.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "senior",
    gender: "male",
    fullName: "Pierre Lefevre",
    hireBlurb:
      "Treats the brand guidelines like a religion: reverent, occasionally inconvenient.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "senior",
    gender: "male",
    fullName: "Russell Boyd",
    hireBlurb: "Schedules a war room that could double as a venue rental.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "senior",
    gender: "female",
    fullName: "Siobhan Murphy",
    hireBlurb: "Ends emails with respectfully and the word carries weight.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "senior",
    gender: "female",
    fullName: "Bridget O'Reilly",
    hireBlurb: "Keeps a who-asked-for-this list that is longer than the brief.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "senior",
    gender: "female",
    fullName: "Francesca Neri",
    hireBlurb:
      "Walks the timeline like a play with three acts and a tragic intermission.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "senior",
    gender: "female",
    fullName: "Gabrielle Monroe",
    hireBlurb: "Refers to launch day as opening night and expects a standing ovation.",
  },
  {
    employeeType: "campaign_manager",
    seniority: "senior",
    gender: "female",
    fullName: "Valerie Chen",
    hireBlurb: 'Says "alignment" like she is signing a treaty.',
  },
];

/**
 * Full names for Talent Bazaar candidates: **exact** role + seniority only (no junior fallback,
 * no cross-tier bleed). Intern uses `seniority: "intern"` (UI passes `campaign_manager` for intern hires).
 */
export function getHiringNamePoolStrings(
  role: "data_analyst" | "campaign_manager" | "sales_representative",
  tier: "intern" | "junior" | "mid" | "senior"
): string[] {
  const seniority: HiringNameSeniority = tier === "intern" ? "intern" : tier;
  return HIRING_NAME_ROWS.filter((r) => r.employeeType === role && r.seniority === seniority).map(
    (r) => r.fullName
  );
}
