/**
 * Canonical Talent Bazaar name roster. One row per person: employee type, seniority,
 * gender (for authoring balance), and display name. Add mid/senior rows later; code
 * Name picks use exact seniority per role (see `getHiringNamePoolStrings`); there is no cross-tier fallback.
 * Mid- and senior-tier rows exist for all three hire roles (no tier-specific Indian skew on senior DA).
 * Interns use `campaign_manager` + `intern` (Talent Bazaar intern mode); diversity is a notch lighter than junior CM.
 *
 * Kept free of imports from `hiring.ts` to avoid circular module graphs.
 */

/** Roles that draw from this table (full roster). `hiring.ts` keeps a small legacy fallback only. */
export type HiringNameEmployeeType = "data_analyst" | "campaign_manager" | "sales_representative";

export type HiringNameSeniority = "intern" | "junior" | "mid" | "senior";

export type HiringNameRow = {
  employeeType: HiringNameEmployeeType;
  seniority: HiringNameSeniority;
  gender: "male" | "female";
  fullName: string;
};

export const HIRING_NAME_ROWS: readonly HiringNameRow[] = [
  // --- Intern · campaign_manager only (40) — UI uses this role for intern hires; 20m / 20f, slightly less global mix than junior CM ---
  { employeeType: "campaign_manager", seniority: "intern", gender: "male", fullName: "Jake Morrison" },
  { employeeType: "campaign_manager", seniority: "intern", gender: "male", fullName: "Tyler Walsh" },
  { employeeType: "campaign_manager", seniority: "intern", gender: "male", fullName: "Brandon Scott" },
  { employeeType: "campaign_manager", seniority: "intern", gender: "male", fullName: "Connor Hayes" },
  { employeeType: "campaign_manager", seniority: "intern", gender: "male", fullName: "Kyle Brennan" },
  { employeeType: "campaign_manager", seniority: "intern", gender: "male", fullName: "Justin Cole" },
  { employeeType: "campaign_manager", seniority: "intern", gender: "male", fullName: "Derek Nash" },
  { employeeType: "campaign_manager", seniority: "intern", gender: "male", fullName: "Trevor Blake" },
  { employeeType: "campaign_manager", seniority: "intern", gender: "male", fullName: "Lucas Finn" },
  { employeeType: "campaign_manager", seniority: "intern", gender: "male", fullName: "Logan Marsh" },
  { employeeType: "campaign_manager", seniority: "intern", gender: "male", fullName: "Marcus Reid" },
  { employeeType: "campaign_manager", seniority: "intern", gender: "male", fullName: "Caleb Stone" },
  { employeeType: "campaign_manager", seniority: "intern", gender: "male", fullName: "Nathaniel Ford" },
  { employeeType: "campaign_manager", seniority: "intern", gender: "male", fullName: "Ryan Archer" },
  { employeeType: "campaign_manager", seniority: "intern", gender: "male", fullName: "Noah Whitaker" },
  { employeeType: "campaign_manager", seniority: "intern", gender: "male", fullName: "Diego Ortiz" },
  { employeeType: "campaign_manager", seniority: "intern", gender: "male", fullName: "Andre Patterson" },
  { employeeType: "campaign_manager", seniority: "intern", gender: "male", fullName: "Ken Yamaguchi" },
  { employeeType: "campaign_manager", seniority: "intern", gender: "male", fullName: "Hassan Malik" },
  { employeeType: "campaign_manager", seniority: "intern", gender: "male", fullName: "Javier Gomez" },
  { employeeType: "campaign_manager", seniority: "intern", gender: "female", fullName: "Emma Walsh" },
  { employeeType: "campaign_manager", seniority: "intern", gender: "female", fullName: "Sarah Blake" },
  { employeeType: "campaign_manager", seniority: "intern", gender: "female", fullName: "Jessica Nash" },
  { employeeType: "campaign_manager", seniority: "intern", gender: "female", fullName: "Ashley Cole" },
  { employeeType: "campaign_manager", seniority: "intern", gender: "female", fullName: "Brittany Ford" },
  { employeeType: "campaign_manager", seniority: "intern", gender: "female", fullName: "Kayla Pierce" },
  { employeeType: "campaign_manager", seniority: "intern", gender: "female", fullName: "Morgan Tierney" },
  { employeeType: "campaign_manager", seniority: "intern", gender: "female", fullName: "Sydney Archer" },
  { employeeType: "campaign_manager", seniority: "intern", gender: "female", fullName: "Taylor Reed" },
  { employeeType: "campaign_manager", seniority: "intern", gender: "female", fullName: "Hailey Shaw" },
  { employeeType: "campaign_manager", seniority: "intern", gender: "female", fullName: "Brooke Marsh" },
  { employeeType: "campaign_manager", seniority: "intern", gender: "female", fullName: "Jenna Holt" },
  { employeeType: "campaign_manager", seniority: "intern", gender: "female", fullName: "Paige Turner" },
  { employeeType: "campaign_manager", seniority: "intern", gender: "female", fullName: "Rylee Cross" },
  { employeeType: "campaign_manager", seniority: "intern", gender: "female", fullName: "Vanessa Ortiz" },
  { employeeType: "campaign_manager", seniority: "intern", gender: "female", fullName: "Monica Reyes" },
  { employeeType: "campaign_manager", seniority: "intern", gender: "female", fullName: "Aya Nakamura" },
  { employeeType: "campaign_manager", seniority: "intern", gender: "female", fullName: "Leila Farah" },
  { employeeType: "campaign_manager", seniority: "intern", gender: "female", fullName: "Natalie Brooks" },
  { employeeType: "campaign_manager", seniority: "intern", gender: "female", fullName: "Ines Marquez" },

  // --- Data Analyst · junior (50) ---
  { employeeType: "data_analyst", seniority: "junior", gender: "male", fullName: "James Whitmore" },
  { employeeType: "data_analyst", seniority: "junior", gender: "male", fullName: "Michael O'Brien" },
  { employeeType: "data_analyst", seniority: "junior", gender: "male", fullName: "Matthew Sullivan" },
  { employeeType: "data_analyst", seniority: "junior", gender: "male", fullName: "Ryan Cooper" },
  { employeeType: "data_analyst", seniority: "junior", gender: "male", fullName: "David Park" },
  { employeeType: "data_analyst", seniority: "junior", gender: "male", fullName: "Chris Andersen" },
  { employeeType: "data_analyst", seniority: "junior", gender: "male", fullName: "Benjamin Hayes" },
  { employeeType: "data_analyst", seniority: "junior", gender: "male", fullName: "Marcus Webb" },
  { employeeType: "data_analyst", seniority: "junior", gender: "male", fullName: "Diego Fernández" },
  { employeeType: "data_analyst", seniority: "junior", gender: "male", fullName: "Amir Hassan" },
  { employeeType: "data_analyst", seniority: "junior", gender: "male", fullName: "Kwesi Mensah" },
  { employeeType: "data_analyst", seniority: "junior", gender: "male", fullName: "Hiro Tanaka" },
  { employeeType: "data_analyst", seniority: "junior", gender: "male", fullName: "Vikram Patel" },
  { employeeType: "data_analyst", seniority: "junior", gender: "male", fullName: "Luca Rossi" },
  { employeeType: "data_analyst", seniority: "junior", gender: "male", fullName: "Omar El-Sayed" },
  { employeeType: "data_analyst", seniority: "junior", gender: "male", fullName: "Javier Morales" },
  { employeeType: "data_analyst", seniority: "junior", gender: "male", fullName: "Andre Thompson" },
  { employeeType: "data_analyst", seniority: "junior", gender: "male", fullName: "Samuel Okonkwo" },
  { employeeType: "data_analyst", seniority: "junior", gender: "male", fullName: "Thomas Mueller" },
  { employeeType: "data_analyst", seniority: "junior", gender: "male", fullName: "Raj Malhotra" },
  { employeeType: "data_analyst", seniority: "junior", gender: "male", fullName: "Daniel Nguyen" },
  { employeeType: "data_analyst", seniority: "junior", gender: "male", fullName: "Ibrahim Farah" },
  { employeeType: "data_analyst", seniority: "junior", gender: "male", fullName: "Sean McCarthy" },
  { employeeType: "data_analyst", seniority: "junior", gender: "male", fullName: "Priyansh Agarwal" },
  { employeeType: "data_analyst", seniority: "junior", gender: "male", fullName: "Ethan Brooks" },
  { employeeType: "data_analyst", seniority: "junior", gender: "female", fullName: "Emily Foster" },
  { employeeType: "data_analyst", seniority: "junior", gender: "female", fullName: "Sarah Mitchell" },
  { employeeType: "data_analyst", seniority: "junior", gender: "female", fullName: "Hannah Becker" },
  { employeeType: "data_analyst", seniority: "junior", gender: "female", fullName: "Rachel Goldman" },
  { employeeType: "data_analyst", seniority: "junior", gender: "female", fullName: "Kate Sullivan" },
  { employeeType: "data_analyst", seniority: "junior", gender: "female", fullName: "Claire Dubois" },
  { employeeType: "data_analyst", seniority: "junior", gender: "female", fullName: "Jessica Moore" },
  { employeeType: "data_analyst", seniority: "junior", gender: "female", fullName: "Olivia Brennan" },
  { employeeType: "data_analyst", seniority: "junior", gender: "female", fullName: "Charlotte Hayes" },
  { employeeType: "data_analyst", seniority: "junior", gender: "female", fullName: "Priya Sharma" },
  { employeeType: "data_analyst", seniority: "junior", gender: "female", fullName: "Maria Santos" },
  { employeeType: "data_analyst", seniority: "junior", gender: "female", fullName: "Yuki Nakamura" },
  { employeeType: "data_analyst", seniority: "junior", gender: "female", fullName: "Fatima Al-Rashid" },
  { employeeType: "data_analyst", seniority: "junior", gender: "female", fullName: "Zoe Campbell" },
  { employeeType: "data_analyst", seniority: "junior", gender: "female", fullName: "Aisha Diallo" },
  { employeeType: "data_analyst", seniority: "junior", gender: "female", fullName: "Elena Vasquez" },
  { employeeType: "data_analyst", seniority: "junior", gender: "female", fullName: "Grace O'Connell" },
  { employeeType: "data_analyst", seniority: "junior", gender: "female", fullName: "Mei Lin" },
  { employeeType: "data_analyst", seniority: "junior", gender: "female", fullName: "Nia Williams" },
  { employeeType: "data_analyst", seniority: "junior", gender: "female", fullName: "Sofia Andersson" },
  { employeeType: "data_analyst", seniority: "junior", gender: "female", fullName: "Ananya Krishnan" },
  { employeeType: "data_analyst", seniority: "junior", gender: "female", fullName: "Layla Haddad" },
  { employeeType: "data_analyst", seniority: "junior", gender: "female", fullName: "Nina Petrova" },
  { employeeType: "data_analyst", seniority: "junior", gender: "female", fullName: "Amara Okafor" },
  { employeeType: "data_analyst", seniority: "junior", gender: "female", fullName: "Isabel Romero" },

  // --- Sales Representative · junior (50) ---
  { employeeType: "sales_representative", seniority: "junior", gender: "male", fullName: "James Whitford" },
  { employeeType: "sales_representative", seniority: "junior", gender: "male", fullName: "Michael Brennan" },
  { employeeType: "sales_representative", seniority: "junior", gender: "male", fullName: "William Cross" },
  { employeeType: "sales_representative", seniority: "junior", gender: "male", fullName: "Christopher Dale" },
  { employeeType: "sales_representative", seniority: "junior", gender: "male", fullName: "Daniel Pryce" },
  { employeeType: "sales_representative", seniority: "junior", gender: "male", fullName: "Patrick Flanagan" },
  { employeeType: "sales_representative", seniority: "junior", gender: "male", fullName: "Gregory Holt" },
  { employeeType: "sales_representative", seniority: "junior", gender: "male", fullName: "Kevin McAllister" },
  { employeeType: "sales_representative", seniority: "junior", gender: "male", fullName: "Tyler Whitman" },
  { employeeType: "sales_representative", seniority: "junior", gender: "male", fullName: "Brandon Keane" },
  { employeeType: "sales_representative", seniority: "junior", gender: "male", fullName: "Luke Harrington" },
  { employeeType: "sales_representative", seniority: "junior", gender: "male", fullName: "Eric Sutton" },
  { employeeType: "sales_representative", seniority: "junior", gender: "male", fullName: "Andrew Pierce" },
  { employeeType: "sales_representative", seniority: "junior", gender: "male", fullName: "Steven Carmichael" },
  { employeeType: "sales_representative", seniority: "junior", gender: "male", fullName: "Jason Whitaker" },
  { employeeType: "sales_representative", seniority: "junior", gender: "male", fullName: "Alejandro Vargas" },
  { employeeType: "sales_representative", seniority: "junior", gender: "male", fullName: "Malik Brooks" },
  { employeeType: "sales_representative", seniority: "junior", gender: "male", fullName: "Rajesh Iyer" },
  { employeeType: "sales_representative", seniority: "junior", gender: "male", fullName: "Hiroshi Okada" },
  { employeeType: "sales_representative", seniority: "junior", gender: "male", fullName: "Darius Webb" },
  { employeeType: "sales_representative", seniority: "junior", gender: "male", fullName: "Omar Nassar" },
  { employeeType: "sales_representative", seniority: "junior", gender: "male", fullName: "Viktor Petrov" },
  { employeeType: "sales_representative", seniority: "junior", gender: "male", fullName: "Kwame Asante" },
  { employeeType: "sales_representative", seniority: "junior", gender: "male", fullName: "Sanjay Mehta" },
  { employeeType: "sales_representative", seniority: "junior", gender: "male", fullName: "Mateo Contreras" },
  { employeeType: "sales_representative", seniority: "junior", gender: "female", fullName: "Ashley Whitmore" },
  { employeeType: "sales_representative", seniority: "junior", gender: "female", fullName: "Brittany Cole" },
  { employeeType: "sales_representative", seniority: "junior", gender: "female", fullName: "Courtney Blake" },
  { employeeType: "sales_representative", seniority: "junior", gender: "female", fullName: "Danielle Foster" },
  { employeeType: "sales_representative", seniority: "junior", gender: "female", fullName: "Jennifer Walsh" },
  { employeeType: "sales_representative", seniority: "junior", gender: "female", fullName: "Kimberly Reed" },
  { employeeType: "sales_representative", seniority: "junior", gender: "female", fullName: "Lauren Thompson" },
  { employeeType: "sales_representative", seniority: "junior", gender: "female", fullName: "Megan O'Connell" },
  { employeeType: "sales_representative", seniority: "junior", gender: "female", fullName: "Nicole Patterson" },
  { employeeType: "sales_representative", seniority: "junior", gender: "female", fullName: "Stephanie Grant" },
  { employeeType: "sales_representative", seniority: "junior", gender: "female", fullName: "Tiffany Brooks" },
  { employeeType: "sales_representative", seniority: "junior", gender: "female", fullName: "Victoria Hayes" },
  { employeeType: "sales_representative", seniority: "junior", gender: "female", fullName: "Heather Vaughn" },
  { employeeType: "sales_representative", seniority: "junior", gender: "female", fullName: "Samantha Blake" },
  { employeeType: "sales_representative", seniority: "junior", gender: "female", fullName: "Madison Clark" },
  { employeeType: "sales_representative", seniority: "junior", gender: "female", fullName: "Priya Kapoor" },
  { employeeType: "sales_representative", seniority: "junior", gender: "female", fullName: "Yuki Tanaka" },
  { employeeType: "sales_representative", seniority: "junior", gender: "female", fullName: "Carmen Vega" },
  { employeeType: "sales_representative", seniority: "junior", gender: "female", fullName: "Fatima Hassan" },
  { employeeType: "sales_representative", seniority: "junior", gender: "female", fullName: "Ingrid Lindberg" },
  { employeeType: "sales_representative", seniority: "junior", gender: "female", fullName: "Zara Ahmed" },
  { employeeType: "sales_representative", seniority: "junior", gender: "female", fullName: "Renee Dubois" },
  { employeeType: "sales_representative", seniority: "junior", gender: "female", fullName: "Monique Johnson" },
  { employeeType: "sales_representative", seniority: "junior", gender: "female", fullName: "Sofia Costa" },
  { employeeType: "sales_representative", seniority: "junior", gender: "female", fullName: "Elena Popov" },

  // --- Campaign Manager · junior (50) — intern hiring uses this role in UI ---
  { employeeType: "campaign_manager", seniority: "junior", gender: "male", fullName: "Nathan Cole" },
  { employeeType: "campaign_manager", seniority: "junior", gender: "male", fullName: "Alex Rivera" },
  { employeeType: "campaign_manager", seniority: "junior", gender: "male", fullName: "Jordan Blake" },
  { employeeType: "campaign_manager", seniority: "junior", gender: "male", fullName: "Felix Mueller" },
  { employeeType: "campaign_manager", seniority: "junior", gender: "male", fullName: "Theo Nakamura" },
  { employeeType: "campaign_manager", seniority: "junior", gender: "male", fullName: "Caleb Oduya" },
  { employeeType: "campaign_manager", seniority: "junior", gender: "male", fullName: "Finn McGregor" },
  { employeeType: "campaign_manager", seniority: "junior", gender: "male", fullName: "Oscar Lindqvist" },
  { employeeType: "campaign_manager", seniority: "junior", gender: "male", fullName: "Rafael Costa" },
  { employeeType: "campaign_manager", seniority: "junior", gender: "male", fullName: "Soren Dahl" },
  { employeeType: "campaign_manager", seniority: "junior", gender: "male", fullName: "Micah Williams" },
  { employeeType: "campaign_manager", seniority: "junior", gender: "male", fullName: "Devon Park" },
  { employeeType: "campaign_manager", seniority: "junior", gender: "male", fullName: "Ellis Zhang" },
  { employeeType: "campaign_manager", seniority: "junior", gender: "male", fullName: "Hugo Bernard" },
  { employeeType: "campaign_manager", seniority: "junior", gender: "male", fullName: "Ian MacLeod" },
  { employeeType: "campaign_manager", seniority: "junior", gender: "male", fullName: "Julian Santos" },
  { employeeType: "campaign_manager", seniority: "junior", gender: "male", fullName: "Kofi Ansah" },
  { employeeType: "campaign_manager", seniority: "junior", gender: "male", fullName: "Rohan Desai" },
  { employeeType: "campaign_manager", seniority: "junior", gender: "male", fullName: "Stefan Vukovic" },
  { employeeType: "campaign_manager", seniority: "junior", gender: "male", fullName: "Tomas Havel" },
  { employeeType: "campaign_manager", seniority: "junior", gender: "male", fullName: "Xavier Moreau" },
  { employeeType: "campaign_manager", seniority: "junior", gender: "male", fullName: "Youssef Mansour" },
  { employeeType: "campaign_manager", seniority: "junior", gender: "male", fullName: "Zain Rahman" },
  { employeeType: "campaign_manager", seniority: "junior", gender: "male", fullName: "Adrian Bloom" },
  { employeeType: "campaign_manager", seniority: "junior", gender: "male", fullName: "Blake Morrison" },
  { employeeType: "campaign_manager", seniority: "junior", gender: "female", fullName: "Emma Clarke" },
  { employeeType: "campaign_manager", seniority: "junior", gender: "female", fullName: "Sophia Nguyen" },
  { employeeType: "campaign_manager", seniority: "junior", gender: "female", fullName: "Mia Torres" },
  { employeeType: "campaign_manager", seniority: "junior", gender: "female", fullName: "Lily Hammond" },
  { employeeType: "campaign_manager", seniority: "junior", gender: "female", fullName: "Nora Fitzgerald" },
  { employeeType: "campaign_manager", seniority: "junior", gender: "female", fullName: "Paige Sullivan" },
  { employeeType: "campaign_manager", seniority: "junior", gender: "female", fullName: "Quinn Harper" },
  { employeeType: "campaign_manager", seniority: "junior", gender: "female", fullName: "Ruby Okonkwo" },
  { employeeType: "campaign_manager", seniority: "junior", gender: "female", fullName: "Stella Ivanova" },
  { employeeType: "campaign_manager", seniority: "junior", gender: "female", fullName: "Tessa Yamamoto" },
  { employeeType: "campaign_manager", seniority: "junior", gender: "female", fullName: "Vera Kowalski" },
  { employeeType: "campaign_manager", seniority: "junior", gender: "female", fullName: "Willow Fraser" },
  { employeeType: "campaign_manager", seniority: "junior", gender: "female", fullName: "Aria Mendez" },
  { employeeType: "campaign_manager", seniority: "junior", gender: "female", fullName: "Bianca Ricci" },
  { employeeType: "campaign_manager", seniority: "junior", gender: "female", fullName: "Dana Al-Farsi" },
  { employeeType: "campaign_manager", seniority: "junior", gender: "female", fullName: "Fiona Walsh" },
  { employeeType: "campaign_manager", seniority: "junior", gender: "female", fullName: "Gia Romano" },
  { employeeType: "campaign_manager", seniority: "junior", gender: "female", fullName: "Hope Adeyemi" },
  { employeeType: "campaign_manager", seniority: "junior", gender: "female", fullName: "Iris van Dijk" },
  { employeeType: "campaign_manager", seniority: "junior", gender: "female", fullName: "Jade Patterson" },
  { employeeType: "campaign_manager", seniority: "junior", gender: "female", fullName: "Kara Lindstrom" },
  { employeeType: "campaign_manager", seniority: "junior", gender: "female", fullName: "Lena Schroeder" },
  { employeeType: "campaign_manager", seniority: "junior", gender: "female", fullName: "Maya Krishnan" },
  { employeeType: "campaign_manager", seniority: "junior", gender: "female", fullName: "Nina Hosseini" },
  { employeeType: "campaign_manager", seniority: "junior", gender: "female", fullName: "Piper Donovan" },

  // --- Data Analyst · mid (30) — higher share of Indian names than junior/other pools ---
  { employeeType: "data_analyst", seniority: "mid", gender: "male", fullName: "Rohan Kapoor" },
  { employeeType: "data_analyst", seniority: "mid", gender: "male", fullName: "Arnav Sinha" },
  { employeeType: "data_analyst", seniority: "mid", gender: "male", fullName: "Vikrant Iyer" },
  { employeeType: "data_analyst", seniority: "mid", gender: "male", fullName: "Karan Thakur" },
  { employeeType: "data_analyst", seniority: "mid", gender: "male", fullName: "Siddharth Bose" },
  { employeeType: "data_analyst", seniority: "mid", gender: "male", fullName: "Aditya Menon" },
  { employeeType: "data_analyst", seniority: "mid", gender: "male", fullName: "James Holloway" },
  { employeeType: "data_analyst", seniority: "mid", gender: "male", fullName: "Michael Tran" },
  { employeeType: "data_analyst", seniority: "mid", gender: "male", fullName: "Carlos Mendez" },
  { employeeType: "data_analyst", seniority: "mid", gender: "male", fullName: "Omar Bakri" },
  { employeeType: "data_analyst", seniority: "mid", gender: "male", fullName: "Kwame Osei" },
  { employeeType: "data_analyst", seniority: "mid", gender: "male", fullName: "Luca Fontana" },
  { employeeType: "data_analyst", seniority: "mid", gender: "male", fullName: "Stefan Weber" },
  { employeeType: "data_analyst", seniority: "mid", gender: "male", fullName: "Hiro Yamane" },
  { employeeType: "data_analyst", seniority: "mid", gender: "male", fullName: "Tomas Novak" },
  { employeeType: "data_analyst", seniority: "mid", gender: "female", fullName: "Anika Reddy" },
  { employeeType: "data_analyst", seniority: "mid", gender: "female", fullName: "Priya Deshpande" },
  { employeeType: "data_analyst", seniority: "mid", gender: "female", fullName: "Kavita Nambiar" },
  { employeeType: "data_analyst", seniority: "mid", gender: "female", fullName: "Sneha Pillai" },
  { employeeType: "data_analyst", seniority: "mid", gender: "female", fullName: "Deepa Venkatesh" },
  { employeeType: "data_analyst", seniority: "mid", gender: "female", fullName: "Meera Krishnan" },
  { employeeType: "data_analyst", seniority: "mid", gender: "female", fullName: "Emma Lindstrom" },
  { employeeType: "data_analyst", seniority: "mid", gender: "female", fullName: "Yuki Sato" },
  { employeeType: "data_analyst", seniority: "mid", gender: "female", fullName: "Laura Giordano" },
  { employeeType: "data_analyst", seniority: "mid", gender: "female", fullName: "Carmen Ibanez" },
  { employeeType: "data_analyst", seniority: "mid", gender: "female", fullName: "Zoe MacKenzie" },
  { employeeType: "data_analyst", seniority: "mid", gender: "female", fullName: "Rachel Matsumoto" },
  { employeeType: "data_analyst", seniority: "mid", gender: "female", fullName: "Olivia Peters" },
  { employeeType: "data_analyst", seniority: "mid", gender: "female", fullName: "Hannah Okafor" },
  { employeeType: "data_analyst", seniority: "mid", gender: "female", fullName: "Nina Hargrove" },

  // --- Sales Representative · mid (30) — Western : diverse ≈ 9 : 6 per gender (same as junior sales 15:10) ---
  { employeeType: "sales_representative", seniority: "mid", gender: "male", fullName: "Mark Thornton" },
  { employeeType: "sales_representative", seniority: "mid", gender: "male", fullName: "Paul Jennings" },
  { employeeType: "sales_representative", seniority: "mid", gender: "male", fullName: "Scott MacKenzie" },
  { employeeType: "sales_representative", seniority: "mid", gender: "male", fullName: "Brian Fletcher" },
  { employeeType: "sales_representative", seniority: "mid", gender: "male", fullName: "Richard Lowe" },
  { employeeType: "sales_representative", seniority: "mid", gender: "male", fullName: "Timothy Hart" },
  { employeeType: "sales_representative", seniority: "mid", gender: "male", fullName: "Adam Morrison" },
  { employeeType: "sales_representative", seniority: "mid", gender: "male", fullName: "Raymond Pierce" },
  { employeeType: "sales_representative", seniority: "mid", gender: "male", fullName: "Kenneth Wade" },
  { employeeType: "sales_representative", seniority: "mid", gender: "male", fullName: "Alejandro Cruz" },
  { employeeType: "sales_representative", seniority: "mid", gender: "male", fullName: "Hiro Nakamura" },
  { employeeType: "sales_representative", seniority: "mid", gender: "male", fullName: "Darius Cole" },
  { employeeType: "sales_representative", seniority: "mid", gender: "male", fullName: "Viktor Kane" },
  { employeeType: "sales_representative", seniority: "mid", gender: "male", fullName: "Kwame Mensah" },
  { employeeType: "sales_representative", seniority: "mid", gender: "male", fullName: "Omar Farouk" },
  { employeeType: "sales_representative", seniority: "mid", gender: "female", fullName: "Ashley Reid" },
  { employeeType: "sales_representative", seniority: "mid", gender: "female", fullName: "Brittany Lane" },
  { employeeType: "sales_representative", seniority: "mid", gender: "female", fullName: "Courtney Wells" },
  { employeeType: "sales_representative", seniority: "mid", gender: "female", fullName: "Danielle Price" },
  { employeeType: "sales_representative", seniority: "mid", gender: "female", fullName: "Jennifer Moss" },
  { employeeType: "sales_representative", seniority: "mid", gender: "female", fullName: "Kimberly Hart" },
  { employeeType: "sales_representative", seniority: "mid", gender: "female", fullName: "Lauren Briggs" },
  { employeeType: "sales_representative", seniority: "mid", gender: "female", fullName: "Megan Frost" },
  { employeeType: "sales_representative", seniority: "mid", gender: "female", fullName: "Nicole Archer" },
  { employeeType: "sales_representative", seniority: "mid", gender: "female", fullName: "Priya Subramanian" },
  { employeeType: "sales_representative", seniority: "mid", gender: "female", fullName: "Yuki Mori" },
  { employeeType: "sales_representative", seniority: "mid", gender: "female", fullName: "Fatima Rahman" },
  { employeeType: "sales_representative", seniority: "mid", gender: "female", fullName: "Ingrid Saastamoinen" },
  { employeeType: "sales_representative", seniority: "mid", gender: "female", fullName: "Zara Malik" },
  { employeeType: "sales_representative", seniority: "mid", gender: "female", fullName: "Elena Stavros" },

  // --- Campaign Manager · mid (30) — same diversity mix as junior CM (Western + global) ---
  { employeeType: "campaign_manager", seniority: "mid", gender: "male", fullName: "Leo Sanford" },
  { employeeType: "campaign_manager", seniority: "mid", gender: "male", fullName: "Maxwell Byrne" },
  { employeeType: "campaign_manager", seniority: "mid", gender: "male", fullName: "Connor Walsh" },
  { employeeType: "campaign_manager", seniority: "mid", gender: "male", fullName: "Ethan Rowan" },
  { employeeType: "campaign_manager", seniority: "mid", gender: "male", fullName: "Owen Fitzgerald" },
  { employeeType: "campaign_manager", seniority: "mid", gender: "male", fullName: "Reid Campbell" },
  { employeeType: "campaign_manager", seniority: "mid", gender: "male", fullName: "Graham Hutchins" },
  { employeeType: "campaign_manager", seniority: "mid", gender: "male", fullName: "Desmond Okoye" },
  { employeeType: "campaign_manager", seniority: "mid", gender: "male", fullName: "Malik Bouazza" },
  { employeeType: "campaign_manager", seniority: "mid", gender: "male", fullName: "Kenzo Aoki" },
  { employeeType: "campaign_manager", seniority: "mid", gender: "male", fullName: "Dante Ferreira" },
  { employeeType: "campaign_manager", seniority: "mid", gender: "male", fullName: "Nico Papadopoulos" },
  { employeeType: "campaign_manager", seniority: "mid", gender: "male", fullName: "Matteo Bernardi" },
  { employeeType: "campaign_manager", seniority: "mid", gender: "male", fullName: "Samir Haddad" },
  { employeeType: "campaign_manager", seniority: "mid", gender: "male", fullName: "Viktor Lindstrom" },
  { employeeType: "campaign_manager", seniority: "mid", gender: "female", fullName: "Chloe Brennan" },
  { employeeType: "campaign_manager", seniority: "mid", gender: "female", fullName: "Harper Whitfield" },
  { employeeType: "campaign_manager", seniority: "mid", gender: "female", fullName: "Ivy Langford" },
  { employeeType: "campaign_manager", seniority: "mid", gender: "female", fullName: "Julianne Meyer" },
  { employeeType: "campaign_manager", seniority: "mid", gender: "female", fullName: "Keira Donovan" },
  { employeeType: "campaign_manager", seniority: "mid", gender: "female", fullName: "Lucia Sandoval" },
  { employeeType: "campaign_manager", seniority: "mid", gender: "female", fullName: "Milena Novak" },
  { employeeType: "campaign_manager", seniority: "mid", gender: "female", fullName: "Naomi Sutherland" },
  { employeeType: "campaign_manager", seniority: "mid", gender: "female", fullName: "Ophelia Reyes" },
  { employeeType: "campaign_manager", seniority: "mid", gender: "female", fullName: "Penelope Shaw" },
  { employeeType: "campaign_manager", seniority: "mid", gender: "female", fullName: "Rowan Gillespie" },
  { employeeType: "campaign_manager", seniority: "mid", gender: "female", fullName: "Selene Park" },
  { employeeType: "campaign_manager", seniority: "mid", gender: "female", fullName: "Talia Benoit" },
  { employeeType: "campaign_manager", seniority: "mid", gender: "female", fullName: "Uma Srinivasan" },
  { employeeType: "campaign_manager", seniority: "mid", gender: "female", fullName: "Wren Holbrook" },

  // --- Data Analyst · senior (10) — even gender split; balanced geography, no Indian over-index ---
  { employeeType: "data_analyst", seniority: "senior", gender: "male", fullName: "Walter Brent" },
  { employeeType: "data_analyst", seniority: "senior", gender: "male", fullName: "Lars Holm" },
  { employeeType: "data_analyst", seniority: "senior", gender: "male", fullName: "Sergei Volkov" },
  { employeeType: "data_analyst", seniority: "senior", gender: "male", fullName: "Enzo Marchetti" },
  { employeeType: "data_analyst", seniority: "senior", gender: "male", fullName: "Sean Tierney" },
  { employeeType: "data_analyst", seniority: "senior", gender: "female", fullName: "Moira Stack" },
  { employeeType: "data_analyst", seniority: "senior", gender: "female", fullName: "Helena Martens" },
  { employeeType: "data_analyst", seniority: "senior", gender: "female", fullName: "Renata Kovacs" },
  { employeeType: "data_analyst", seniority: "senior", gender: "female", fullName: "Diane Kehoe" },
  { employeeType: "data_analyst", seniority: "senior", gender: "female", fullName: "Elin Svendsen" },

  // --- Sales Representative · senior (10) — even gender split ---
  { employeeType: "sales_representative", seniority: "senior", gender: "male", fullName: "Douglas Shaw" },
  { employeeType: "sales_representative", seniority: "senior", gender: "male", fullName: "Philip Grant" },
  { employeeType: "sales_representative", seniority: "senior", gender: "male", fullName: "Kenji Moriwaki" },
  { employeeType: "sales_representative", seniority: "senior", gender: "male", fullName: "Russell Tate" },
  { employeeType: "sales_representative", seniority: "senior", gender: "male", fullName: "Craig Hodges" },
  { employeeType: "sales_representative", seniority: "senior", gender: "female", fullName: "Deborah Klein" },
  { employeeType: "sales_representative", seniority: "senior", gender: "female", fullName: "Victoria Lang" },
  { employeeType: "sales_representative", seniority: "senior", gender: "female", fullName: "Sandra Moss" },
  { employeeType: "sales_representative", seniority: "senior", gender: "female", fullName: "Luisa Ordonez" },
  { employeeType: "sales_representative", seniority: "senior", gender: "female", fullName: "Janet Calder" },

  // --- Campaign Manager · senior (10) — even gender split ---
  { employeeType: "campaign_manager", seniority: "senior", gender: "male", fullName: "Garrett Sloan" },
  { employeeType: "campaign_manager", seniority: "senior", gender: "male", fullName: "Mitchell Crane" },
  { employeeType: "campaign_manager", seniority: "senior", gender: "male", fullName: "Declan Riordan" },
  { employeeType: "campaign_manager", seniority: "senior", gender: "male", fullName: "Pierre Lefevre" },
  { employeeType: "campaign_manager", seniority: "senior", gender: "male", fullName: "Russell Boyd" },
  { employeeType: "campaign_manager", seniority: "senior", gender: "female", fullName: "Siobhan Murphy" },
  { employeeType: "campaign_manager", seniority: "senior", gender: "female", fullName: "Bridget O'Reilly" },
  { employeeType: "campaign_manager", seniority: "senior", gender: "female", fullName: "Francesca Neri" },
  { employeeType: "campaign_manager", seniority: "senior", gender: "female", fullName: "Gabrielle Monroe" },
  { employeeType: "campaign_manager", seniority: "senior", gender: "female", fullName: "Valerie Chen" },
];

/**
 * Full names for Talent Bazaar candidates: **exact** role + seniority only (no junior fallback,
 * no cross-tier bleed). Intern uses `seniority: "intern"` (UI passes `campaign_manager` for intern hires).
 */
export function getHiringNamePoolStrings(
  role: "data_analyst" | "campaign_manager" | "sales_representative",
  tier: "intern" | "junior" | "mid" | "senior"
): string[] {
  const seniority: HiringNameSeniority = tier === "intern" ? "intern" : tier;
  return HIRING_NAME_ROWS.filter((r) => r.employeeType === role && r.seniority === seniority).map(
    (r) => r.fullName
  );
}
