-- Employee generation reference data
-- Adds:
-- 1) Random name pool (diverse male/female list)
-- 2) Description templates by tier/role/salary band

create table if not exists public.employee_name_pool (
  id bigint generated always as identity primary key,
  full_name text not null unique,
  gender text not null check (gender in ('male', 'female')),
  created_at timestamptz not null default now()
);

create table if not exists public.employee_description_templates (
  id uuid primary key default gen_random_uuid(),
  tier text not null check (tier in ('intern', 'junior', 'mid', 'senior')),
  role text check (role in ('data_analyst', 'campaign_manager', 'sales_representative')),
  salary_band_index smallint check (salary_band_index between 1 and 5),
  salary_anchor_k smallint check (salary_anchor_k >= 0),
  template_text text not null,
  created_at timestamptz not null default now(),
  check (
    (tier = 'intern' and role is null and salary_band_index is null and salary_anchor_k is null)
    or
    (tier <> 'intern' and role is not null and salary_band_index is not null and salary_anchor_k is not null)
  )
);

alter table public.employee_name_pool enable row level security;
alter table public.employee_description_templates enable row level security;

create policy "employee_name_pool_select_public"
  on public.employee_name_pool for select
  to anon, authenticated
  using (true);

create policy "employee_description_templates_select_public"
  on public.employee_description_templates for select
  to anon, authenticated
  using (true);

insert into public.employee_name_pool (full_name, gender) values
  ('Liam Carter', 'male'),
  ('Noah Kim', 'male'),
  ('Ethan Patel', 'male'),
  ('Mason Okafor', 'male'),
  ('Lucas Silva', 'male'),
  ('Aiden Novak', 'male'),
  ('Elijah Mensah', 'male'),
  ('Mateo Alvarez', 'male'),
  ('Daniel Rossi', 'male'),
  ('Arjun Rao', 'male'),
  ('Rayan Haddad', 'male'),
  ('Yusuf Diallo', 'male'),
  ('Jinwoo Park', 'male'),
  ('Omar Rahman', 'male'),
  ('Zayd Khan', 'male'),
  ('Ivan Petrov', 'male'),
  ('Nikolai Sokolov', 'male'),
  ('Tomasz Lewandowski', 'male'),
  ('Marek Novak', 'male'),
  ('Andrei Ionescu', 'male'),
  ('Santiago Cruz', 'male'),
  ('Thiago Lima', 'male'),
  ('Diego Morales', 'male'),
  ('Rafael Duarte', 'male'),
  ('Emiliano Vega', 'male'),
  ('Kenji Tanaka', 'male'),
  ('Haruto Sato', 'male'),
  ('Minjun Lee', 'male'),
  ('Wei Chen', 'male'),
  ('Yichen Zhang', 'male'),
  ('Aniket Deshmukh', 'male'),
  ('Kabir Mehta', 'male'),
  ('Rohit Nair', 'male'),
  ('Pranav Iyer', 'male'),
  ('Aarav Bhat', 'male'),
  ('Hamza Qureshi', 'male'),
  ('Bilal Siddiqui', 'male'),
  ('Faris Mansour', 'male'),
  ('Tariq Khalil', 'male'),
  ('Karim Nasser', 'male'),
  ('Samuel Johnson', 'male'),
  ('Benjamin Wright', 'male'),
  ('Alexander Moore', 'male'),
  ('Henry Walker', 'male'),
  ('Jack Thompson', 'male'),
  ('Oliver Bennett', 'male'),
  ('Theo Martin', 'male'),
  ('Julian Reid', 'male'),
  ('Caleb Brooks', 'male'),
  ('Isaac Perry', 'male'),
  ('Musa Abubakar', 'male'),
  ('Kwame Boateng', 'male'),
  ('Thabo Ndlovu', 'male'),
  ('Tendai Moyo', 'male'),
  ('Kofi Asante', 'male'),
  ('Ahmed El-Sayed', 'male'),
  ('Mustafa Yilmaz', 'male'),
  ('Emir Demir', 'male'),
  ('Pavel Horvat', 'male'),
  ('Luka Kovac', 'male'),
  ('Jonas Berg', 'male'),
  ('Lars Nielsen', 'male'),
  ('Soren Mikkelsen', 'male'),
  ('Mikko Laine', 'male'),
  ('Eero Virtanen', 'male'),
  ('George Papadopoulos', 'male'),
  ('Nikos Stavros', 'male'),
  ('Petar Dimitrov', 'male'),
  ('Viktor Markovic', 'male'),
  ('Sergei Orlov', 'male'),
  ('Hugo Ferreira', 'male'),
  ('Bruno Teixeira', 'male'),
  ('Leonardo Costa', 'male'),
  ('Felipe Andrade', 'male'),
  ('Caio Mendes', 'male'),
  ('Enzo Gallo', 'male'),
  ('Matteo Ricci', 'male'),
  ('Giovanni Conti', 'male'),
  ('Lorenzo Bianchi', 'male'),
  ('Mehdi Azizi', 'male'),
  ('Reza Farhadi', 'male'),
  ('Saeed Alvi', 'male'),
  ('Naveed Akhtar', 'male'),
  ('Imran Bashir', 'male'),
  ('Bekzod Karimov', 'male'),
  ('Rustam Aliyev', 'male'),
  ('Daniyar Sarsembayev', 'male'),
  ('Batu Erden', 'male'),
  ('Temur Iskandar', 'male'),
  ('Hector Salazar', 'male'),
  ('Martin Delgado', 'male'),
  ('Javier Ponce', 'male'),
  ('Alonso Ibanez', 'male'),
  ('Cristian Flores', 'male'),
  ('Miguel Herrera', 'male'),
  ('Adrian Lozano', 'male'),
  ('Esteban Rojas', 'male'),
  ('Nolan Price', 'male'),
  ('Ryan Sullivan', 'male'),
  ('Ava Nguyen', 'female'),
  ('Mia Chen', 'female'),
  ('Sophia Kim', 'female'),
  ('Isabella Patel', 'female'),
  ('Emma Okafor', 'female'),
  ('Olivia Silva', 'female'),
  ('Aria Novak', 'female'),
  ('Layla Mensah', 'female'),
  ('Zoe Alvarez', 'female'),
  ('Nora Rossi', 'female'),
  ('Ananya Rao', 'female'),
  ('Sana Haddad', 'female'),
  ('Yasmin Khan', 'female'),
  ('Aisha Rahman', 'female'),
  ('Fatima Diallo', 'female'),
  ('Hana Park', 'female'),
  ('Yuna Sato', 'female'),
  ('Mei Zhang', 'female'),
  ('Rin Tanaka', 'female'),
  ('Soojin Lee', 'female'),
  ('Camila Cruz', 'female'),
  ('Valentina Morales', 'female'),
  ('Lucia Vega', 'female'),
  ('Mariana Duarte', 'female'),
  ('Bianca Lima', 'female'),
  ('Giulia Ricci', 'female'),
  ('Francesca Conti', 'female'),
  ('Elena Bianchi', 'female'),
  ('Katarzyna Nowak', 'female'),
  ('Zofia Kowalska', 'female'),
  ('Anastasia Petrova', 'female'),
  ('Irina Sokolova', 'female'),
  ('Ioana Ionescu', 'female'),
  ('Petra Horvat', 'female'),
  ('Nina Kovac', 'female'),
  ('Amara Ndlovu', 'female'),
  ('Zuri Abubakar', 'female'),
  ('Ama Boateng', 'female'),
  ('Thandi Moyo', 'female'),
  ('Nneka Asante', 'female'),
  ('Leila El-Sayed', 'female'),
  ('Derya Yilmaz', 'female'),
  ('Selin Demir', 'female'),
  ('Meryem Mansour', 'female'),
  ('Rania Nasser', 'female'),
  ('Priya Deshmukh', 'female'),
  ('Ishita Mehta', 'female'),
  ('Kavya Nair', 'female'),
  ('Diya Iyer', 'female'),
  ('Aarohi Bhat', 'female'),
  ('Mariam Qureshi', 'female'),
  ('Noor Siddiqui', 'female'),
  ('Shireen Alvi', 'female'),
  ('Sadia Akhtar', 'female'),
  ('Imani Johnson', 'female'),
  ('Chloe Wright', 'female'),
  ('Grace Moore', 'female'),
  ('Lily Walker', 'female'),
  ('Scarlett Thompson', 'female'),
  ('Hazel Bennett', 'female'),
  ('Ruby Martin', 'female'),
  ('Ella Reid', 'female'),
  ('Madison Brooks', 'female'),
  ('Naomi Perry', 'female'),
  ('Elif Azizi', 'female'),
  ('Parisa Farhadi', 'female'),
  ('Samira Bashir', 'female'),
  ('Amina Khalil', 'female'),
  ('Huda Rahimi', 'female'),
  ('Aylin Erden', 'female'),
  ('Madina Karimova', 'female'),
  ('Aizada Sarsembayeva', 'female'),
  ('Dinara Iskandar', 'female'),
  ('Gulnara Aliyeva', 'female'),
  ('Marta Delgado', 'female'),
  ('Sofia Ponce', 'female'),
  ('Daniela Ibanez', 'female'),
  ('Paula Flores', 'female'),
  ('Ines Herrera', 'female'),
  ('Rocio Lozano', 'female'),
  ('Valeria Rojas', 'female'),
  ('Carmen Salazar', 'female'),
  ('Alma Ferreira', 'female'),
  ('Bruna Teixeira', 'female'),
  ('Larissa Costa', 'female'),
  ('Isadora Andrade', 'female'),
  ('Nadia Papadopoulos', 'female'),
  ('Eleni Stavrou', 'female'),
  ('Mila Dimitrova', 'female'),
  ('Sonja Markovic', 'female'),
  ('Tove Berg', 'female'),
  ('Freja Nielsen', 'female'),
  ('Ida Mikkelsen', 'female'),
  ('Aino Laine', 'female'),
  ('Silja Virtanen', 'female'),
  ('Yvette Adeyemi', 'female'),
  ('Farah Bensaid', 'female'),
  ('Jade Okoye', 'female'),
  ('Noelle Mensima', 'female'),
  ('Hiba Amrani', 'female')
on conflict (full_name) do nothing;

-- Intern descriptions (fixed tier, no role or salary band)
insert into public.employee_description_templates (tier, role, salary_band_index, salary_anchor_k, template_text) values
  ('intern', null, null, null, 'Eager, under-caffeinated, and somehow already running three tabs of crisis notes.'),
  ('intern', null, null, null, 'Learns fast, asks good questions, and color-codes panic into action items.'),
  ('intern', null, null, null, 'New to PR, but has a suspiciously strong instinct for what not to post.'),
  ('intern', null, null, null, 'Still figuring out office politics, but excellent at catching obvious narrative leaks.'),
  ('intern', null, null, null, 'Brings fresh eyes, quick hands, and zero fear of impossible deadlines.')
on conflict do nothing;

-- Junior bands (1..5 anchors: 15,20,25,30,35)
insert into public.employee_description_templates (tier, role, salary_band_index, salary_anchor_k, template_text) values
  ('junior', 'sales_representative', 1, 15, 'Knows how to get attention, even if the plan arrives five minutes later.'),
  ('junior', 'sales_representative', 1, 15, 'Great at opening doors, average at closing loops, improving every campaign.'),
  ('junior', 'sales_representative', 1, 15, 'Brings energy, bold pitches, and a talent for finding reachable audiences.'),
  ('junior', 'sales_representative', 1, 15, 'Can sell a shaky idea confidently, then asks strategy to make it true.'),
  ('junior', 'sales_representative', 1, 15, 'Strong crowd instincts with just enough discipline to stay on-message.'),
  ('junior', 'data_analyst', 1, 15, 'Turns messy data into useful signals, with occasional overconfidence in spreadsheets.'),
  ('junior', 'data_analyst', 1, 15, 'Solid pattern spotter who flags risks before they become headlines.'),
  ('junior', 'data_analyst', 1, 15, 'Better at evidence than flair, which is exactly what some crises need.'),
  ('junior', 'data_analyst', 1, 15, 'Brings structure to chaos and asks the uncomfortable but necessary questions.'),
  ('junior', 'data_analyst', 1, 15, 'Finds what matters fast, then backs it with clean, defendable analysis.'),
  ('junior', 'campaign_manager', 1, 15, 'Keeps plans moving, teams aligned, and disasters mostly on schedule.'),
  ('junior', 'campaign_manager', 1, 15, 'Balances narrative and execution without overcomplicating either.'),
  ('junior', 'campaign_manager', 1, 15, 'Not flashy, but dependable when campaigns need coordination under pressure.'),
  ('junior', 'campaign_manager', 1, 15, 'Good at translating big ideas into tasks people can actually finish.'),
  ('junior', 'campaign_manager', 1, 15, 'Brings practical campaign rhythm: brief, execute, adjust, repeat.'),

  ('junior', 'sales_representative', 2, 20, 'Brings sharper outreach instincts and knows which audiences convert into momentum.'),
  ('junior', 'sales_representative', 2, 20, 'Confident pitcher with improving follow-through and better channel discipline.'),
  ('junior', 'sales_representative', 2, 20, 'Can generate buzz without burning credibility every single time.'),
  ('junior', 'sales_representative', 2, 20, 'Good at timing, decent at framing, and noticeably stronger under pressure.'),
  ('junior', 'sales_representative', 2, 20, 'Starts campaigns fast, then adapts quickly when public mood shifts mid-cycle.'),
  ('junior', 'data_analyst', 2, 20, 'Produces cleaner reads, faster risk flags, and fewer false alarms.'),
  ('junior', 'data_analyst', 2, 20, 'Good at translating numbers into decisions non-analysts can actually use.'),
  ('junior', 'data_analyst', 2, 20, 'Spots narrative drift early and recommends practical corrections.'),
  ('junior', 'data_analyst', 2, 20, 'More reliable with ambiguous data and less likely to chase noise.'),
  ('junior', 'data_analyst', 2, 20, 'Builds trust by being precise, calm, and usually right for the right reasons.'),
  ('junior', 'campaign_manager', 2, 20, 'Coordinates teams with less friction and keeps execution aligned to strategy.'),
  ('junior', 'campaign_manager', 2, 20, 'Better at turning broad goals into concrete campaign steps.'),
  ('junior', 'campaign_manager', 2, 20, 'Handles deadline pressure well and keeps quality from collapsing late.'),
  ('junior', 'campaign_manager', 2, 20, 'Stronger cross-functional communicator with fewer dropped handoffs.'),
  ('junior', 'campaign_manager', 2, 20, 'Brings steady structure to chaotic campaigns without slowing momentum.'),

  ('junior', 'sales_representative', 3, 25, 'Reads room temperature quickly and pivots outreach before momentum fades.'),
  ('junior', 'sales_representative', 3, 25, 'Consistently finds viable audience pockets and converts them into campaign lift.'),
  ('junior', 'sales_representative', 3, 25, 'Learns platform nuance fast and avoids most rookie amplification mistakes.'),
  ('junior', 'sales_representative', 3, 25, 'Brings measurable reach gains with improving narrative discipline.'),
  ('junior', 'sales_representative', 3, 25, 'Comfortable under scrutiny and rarely rattled by public pushback.'),
  ('junior', 'data_analyst', 3, 25, 'Delivers actionable insights, not just pretty charts and cautious caveats.'),
  ('junior', 'data_analyst', 3, 25, 'Separates trend from noise with confidence and useful timing.'),
  ('junior', 'data_analyst', 3, 25, 'Combines quantitative reads with practical campaign recommendations.'),
  ('junior', 'data_analyst', 3, 25, 'Strong at pre-empting avoidable PR errors through early signal checks.'),
  ('junior', 'data_analyst', 3, 25, 'Reliable analyst with growing strategic awareness beyond raw metrics.'),
  ('junior', 'campaign_manager', 3, 25, 'Runs cleaner briefs and keeps dependencies visible before they explode.'),
  ('junior', 'campaign_manager', 3, 25, 'Translates strategy into execution plans teams actually follow.'),
  ('junior', 'campaign_manager', 3, 25, 'Good at balancing urgency with quality during noisy campaign weeks.'),
  ('junior', 'campaign_manager', 3, 25, 'Builds alignment across teams without turning meetings into marathons.'),
  ('junior', 'campaign_manager', 3, 25, 'Routinely keeps campaigns moving when others stall in ambiguity.'),

  ('junior', 'sales_representative', 4, 30, 'Reliable generator of reach spikes with fewer unforced messaging errors.'),
  ('junior', 'sales_representative', 4, 30, 'Understands positioning and can sell nuance, not just volume.'),
  ('junior', 'sales_representative', 4, 30, 'Turns modest budgets into visible traction through focused targeting.'),
  ('junior', 'sales_representative', 4, 30, 'Confident in high-pressure outreach without drifting off strategy.'),
  ('junior', 'sales_representative', 4, 30, 'Brings disciplined energy and audience instincts that usually pay off.'),
  ('junior', 'data_analyst', 4, 30, 'Accurate, fast, and practical when campaigns need clear evidence now.'),
  ('junior', 'data_analyst', 4, 30, 'Improves decision quality by framing what matters and why.'),
  ('junior', 'data_analyst', 4, 30, 'Excellent at identifying weak assumptions before launch.'),
  ('junior', 'data_analyst', 4, 30, 'Trusted for high-signal analysis during uncertain public reactions.'),
  ('junior', 'data_analyst', 4, 30, 'Can challenge shaky narratives with facts people actually understand.'),
  ('junior', 'campaign_manager', 4, 30, 'Keeps campaign machinery humming without sacrificing strategic intent.'),
  ('junior', 'campaign_manager', 4, 30, 'Very good at cross-team sequencing and deadline stability.'),
  ('junior', 'campaign_manager', 4, 30, 'Prevents small coordination issues from becoming expensive public mistakes.'),
  ('junior', 'campaign_manager', 4, 30, 'Brings structure, urgency, and surprisingly calm crisis execution.'),
  ('junior', 'campaign_manager', 4, 30, 'Strong operator with growing instincts for message discipline.'),

  ('junior', 'sales_representative', 5, 35, 'Top-end junior who can build momentum and sustain it responsibly.'),
  ('junior', 'sales_representative', 5, 35, 'Drives reach with clear audience intent and minimal wasted spend.'),
  ('junior', 'sales_representative', 5, 35, 'Balances bold outreach with enough restraint to protect reputation.'),
  ('junior', 'sales_representative', 5, 35, 'Produces consistent visibility gains even in crowded narrative windows.'),
  ('junior', 'sales_representative', 5, 35, 'Likely to outperform this tier if managed well.'),
  ('junior', 'data_analyst', 5, 35, 'Top-end junior analyst with mature judgment under messy conditions.'),
  ('junior', 'data_analyst', 5, 35, 'Turns uncertainty into clear options with minimal hand-holding.'),
  ('junior', 'data_analyst', 5, 35, 'Catches subtle risk signals that many teams miss.'),
  ('junior', 'data_analyst', 5, 35, 'High-confidence analysis that sharpens strategy without slowing pace.'),
  ('junior', 'data_analyst', 5, 35, 'A strong foundation hire for long-term capability building.'),
  ('junior', 'campaign_manager', 5, 35, 'Top-end junior manager who keeps outcomes and execution tightly linked.'),
  ('junior', 'campaign_manager', 5, 35, 'Excellent at making complex campaigns feel organized and doable.'),
  ('junior', 'campaign_manager', 5, 35, 'Consistent, proactive, and very hard to knock off plan.'),
  ('junior', 'campaign_manager', 5, 35, 'Bridges strategy and delivery better than most in this tier.'),
  ('junior', 'campaign_manager', 5, 35, 'Often the reason chaotic weeks still end in acceptable outcomes.')
on conflict do nothing;

-- Mid bands (1..5 anchors: 40,45,50,55,60)
insert into public.employee_description_templates (tier, role, salary_band_index, salary_anchor_k, template_text) values
  ('mid', 'sales_representative', 1, 40, 'Steady reach builder with better judgment on when not to amplify.'),
  ('mid', 'sales_representative', 1, 40, 'Knows platform dynamics and can scale attention without instant backlash.'),
  ('mid', 'sales_representative', 1, 40, 'Confident operator who improves visibility while keeping message discipline.'),
  ('mid', 'sales_representative', 1, 40, 'Finds practical growth channels and avoids most vanity plays.'),
  ('mid', 'sales_representative', 1, 40, 'Useful mid-level closer for campaigns needing controlled momentum.'),
  ('mid', 'data_analyst', 1, 40, 'Delivers crisp insight packages that strategy can act on immediately.'),
  ('mid', 'data_analyst', 1, 40, 'Reliable with mixed signals and strong at scenario framing.'),
  ('mid', 'data_analyst', 1, 40, 'Pairs evidence quality with business reality better than most.'),
  ('mid', 'data_analyst', 1, 40, 'Good at predicting where narratives might crack next.'),
  ('mid', 'data_analyst', 1, 40, 'A practical thinker who rarely overfits to noisy data.'),
  ('mid', 'campaign_manager', 1, 40, 'Runs campaigns with solid tempo and fewer coordination leaks.'),
  ('mid', 'campaign_manager', 1, 40, 'Comfortable owning multi-stream execution in imperfect conditions.'),
  ('mid', 'campaign_manager', 1, 40, 'Maintains quality under pressure without freezing decision velocity.'),
  ('mid', 'campaign_manager', 1, 40, 'Strong planner who keeps teams aligned around real priorities.'),
  ('mid', 'campaign_manager', 1, 40, 'Dependable mid-tier anchor for operational stability.'),

  ('mid', 'sales_representative', 2, 45, 'Builds attention strategically, not just loudly, with good conversion instincts.'),
  ('mid', 'sales_representative', 2, 45, 'Balances speed and narrative consistency across changing audience moods.'),
  ('mid', 'sales_representative', 2, 45, 'Good at channel orchestration and timing critical visibility pushes.'),
  ('mid', 'sales_representative', 2, 45, 'Produces repeatable outreach wins with fewer cleanup costs.'),
  ('mid', 'sales_representative', 2, 45, 'A strong mid-tier pick for dependable growth campaigns.'),
  ('mid', 'data_analyst', 2, 45, 'Sharper diagnostics and cleaner recommendations under deadline pressure.'),
  ('mid', 'data_analyst', 2, 45, 'Finds leverage points quickly and supports them with credible evidence.'),
  ('mid', 'data_analyst', 2, 45, 'Rarely misses emerging risk pockets in segmented audiences.'),
  ('mid', 'data_analyst', 2, 45, 'Can challenge assumptions without derailing momentum.'),
  ('mid', 'data_analyst', 2, 45, 'Strong analytical partner for strategy-heavy campaign decisions.'),
  ('mid', 'campaign_manager', 2, 45, 'Improves delivery reliability and keeps cross-team drift in check.'),
  ('mid', 'campaign_manager', 2, 45, 'Very good at sequencing work when stakes rise quickly.'),
  ('mid', 'campaign_manager', 2, 45, 'Protects campaign quality by managing tradeoffs transparently.'),
  ('mid', 'campaign_manager', 2, 45, 'Turns broad strategic goals into efficient, trackable execution.'),
  ('mid', 'campaign_manager', 2, 45, 'Strong operations bridge between analysts, strategists, and outreach.'),

  ('mid', 'sales_representative', 3, 50, 'High-output seller with disciplined positioning and audience fit.'),
  ('mid', 'sales_representative', 3, 50, 'Scales reach while preserving enough credibility for round-two stability.'),
  ('mid', 'sales_representative', 3, 50, 'Adept at converting visibility opportunities into measurable campaign lift.'),
  ('mid', 'sales_representative', 3, 50, 'Can recover outreach trajectories after early narrative stumbles.'),
  ('mid', 'sales_representative', 3, 50, 'A quality mid-tier choice for ambitious but controlled growth.'),
  ('mid', 'data_analyst', 3, 50, 'Consistently high-signal analyst with practical strategic instincts.'),
  ('mid', 'data_analyst', 3, 50, 'Excellent at identifying when a campaign is convincing but unstable.'),
  ('mid', 'data_analyst', 3, 50, 'Builds confidence across teams by making complexity legible.'),
  ('mid', 'data_analyst', 3, 50, 'Strong quantitative backbone for high-variance crisis scenarios.'),
  ('mid', 'data_analyst', 3, 50, 'Frequently turns uncertain data into clear decision paths.'),
  ('mid', 'campaign_manager', 3, 50, 'Keeps high-stakes campaigns coherent across speed, quality, and scope.'),
  ('mid', 'campaign_manager', 3, 50, 'Excellent at de-risking execution before issues go public.'),
  ('mid', 'campaign_manager', 3, 50, 'Leads coordinated pivots without losing team alignment.'),
  ('mid', 'campaign_manager', 3, 50, 'A calm operator who upgrades campaign consistency quickly.'),
  ('mid', 'campaign_manager', 3, 50, 'Strong mid-tier manager with near-senior execution discipline.'),

  ('mid', 'sales_representative', 4, 55, 'Can engineer sustained visibility runs with fewer volatility spikes.'),
  ('mid', 'sales_representative', 4, 55, 'Understands when to press reach and when to protect narrative trust.'),
  ('mid', 'sales_representative', 4, 55, 'Skilled at targeted amplification in competitive attention markets.'),
  ('mid', 'sales_representative', 4, 55, 'Delivers high tempo outreach without constant strategic supervision.'),
  ('mid', 'sales_representative', 4, 55, 'A top mid-band pick for campaigns that need scale and restraint.'),
  ('mid', 'data_analyst', 4, 55, 'High-clarity analyst who improves both decision speed and quality.'),
  ('mid', 'data_analyst', 4, 55, 'Excellent at stress-testing campaign logic before public launch.'),
  ('mid', 'data_analyst', 4, 55, 'Finds second-order risks that usually surface too late.'),
  ('mid', 'data_analyst', 4, 55, 'Reliable source of insight during noisy, politically charged cycles.'),
  ('mid', 'data_analyst', 4, 55, 'A strong stabilizer for competence-heavy agency builds.'),
  ('mid', 'campaign_manager', 4, 55, 'Runs dense campaign portfolios with very little process drag.'),
  ('mid', 'campaign_manager', 4, 55, 'Great at resolving inter-team friction before it harms output.'),
  ('mid', 'campaign_manager', 4, 55, 'Maintains delivery confidence through fast-changing external conditions.'),
  ('mid', 'campaign_manager', 4, 55, 'Can keep strategy, messaging, and execution tightly synchronized.'),
  ('mid', 'campaign_manager', 4, 55, 'High-value operational core for scaling agencies.'),

  ('mid', 'sales_representative', 5, 60, 'Elite mid-tier reach specialist with disciplined campaign instincts.'),
  ('mid', 'sales_representative', 5, 60, 'Frequently outperforms tier expectations in controlled growth scenarios.'),
  ('mid', 'sales_representative', 5, 60, 'Generates visibility efficiently without flooding low-fit segments.'),
  ('mid', 'sales_representative', 5, 60, 'Strong finisher for agencies pushing larger narrative plays.'),
  ('mid', 'sales_representative', 5, 60, 'Near-senior upside when paired with clear strategic direction.'),
  ('mid', 'data_analyst', 5, 60, 'Top mid-tier analyst with high trust and strong strategic utility.'),
  ('mid', 'data_analyst', 5, 60, 'Converts complex audience signals into repeatable advantage.'),
  ('mid', 'data_analyst', 5, 60, 'Consistently elevates campaign quality through precise insight framing.'),
  ('mid', 'data_analyst', 5, 60, 'Near-senior impact on competence-heavy decision environments.'),
  ('mid', 'data_analyst', 5, 60, 'A premium mid-band hire for long-term analytical strength.'),
  ('mid', 'campaign_manager', 5, 60, 'Top mid-tier campaign lead with polished execution discipline.'),
  ('mid', 'campaign_manager', 5, 60, 'Combines strategic alignment and delivery pace exceptionally well.'),
  ('mid', 'campaign_manager', 5, 60, 'Frequently prevents expensive mistakes through proactive orchestration.'),
  ('mid', 'campaign_manager', 5, 60, 'Near-senior reliability without full senior payroll cost.'),
  ('mid', 'campaign_manager', 5, 60, 'A premium operator for agencies entering heavier campaign loads.')
on conflict do nothing;

-- Senior bands (1..5 anchors: 65,70,75,80,85)
insert into public.employee_description_templates (tier, role, salary_band_index, salary_anchor_k, template_text) values
  ('senior', 'sales_representative', 1, 65, 'Veteran reach architect who can scale visibility without losing message control.'),
  ('senior', 'sales_representative', 1, 65, 'Strong senior seller with disciplined audience targeting and timing.'),
  ('senior', 'sales_representative', 1, 65, 'Experienced at building momentum in crowded, hostile narrative spaces.'),
  ('senior', 'sales_representative', 1, 65, 'Brings strategic amplification instincts and fewer avoidable blowups.'),
  ('senior', 'sales_representative', 1, 65, 'A serious visibility upgrade for agencies ready for bigger stages.'),
  ('senior', 'data_analyst', 1, 65, 'Senior analyst who turns messy public sentiment into actionable confidence.'),
  ('senior', 'data_analyst', 1, 65, 'Strong at detecting fragility in plans that look good on paper.'),
  ('senior', 'data_analyst', 1, 65, 'Delivers high-trust analysis across volatile campaign environments.'),
  ('senior', 'data_analyst', 1, 65, 'Balances speed and rigor without sacrificing decision quality.'),
  ('senior', 'data_analyst', 1, 65, 'A major competence anchor for high-stakes runs.'),
  ('senior', 'campaign_manager', 1, 65, 'Senior campaign operator who keeps complex execution surprisingly stable.'),
  ('senior', 'campaign_manager', 1, 65, 'Excellent at aligning strategy, teams, and delivery under pressure.'),
  ('senior', 'campaign_manager', 1, 65, 'Reduces operational entropy before it becomes public damage.'),
  ('senior', 'campaign_manager', 1, 65, 'Strong senior pick for agencies scaling multi-client load.'),
  ('senior', 'campaign_manager', 1, 65, 'A proven stabilizer in campaigns with many moving parts.'),

  ('senior', 'sales_representative', 2, 70, 'High-impact senior who can sustain attention without burning trust instantly.'),
  ('senior', 'sales_representative', 2, 70, 'Skilled at cross-channel pressure plays with measured narrative risk.'),
  ('senior', 'sales_representative', 2, 70, 'Turns visibility surges into durable campaign leverage.'),
  ('senior', 'sales_representative', 2, 70, 'Frequently wins contested audience battles through positioning discipline.'),
  ('senior', 'sales_representative', 2, 70, 'Premium senior outreach lead for aggressive growth plans.'),
  ('senior', 'data_analyst', 2, 70, 'Premium senior analyst with exceptional signal detection under uncertainty.'),
  ('senior', 'data_analyst', 2, 70, 'Can diagnose campaign weakness before metrics fully confirm it.'),
  ('senior', 'data_analyst', 2, 70, 'Produces strategic clarity when teams are split on direction.'),
  ('senior', 'data_analyst', 2, 70, 'Rare mix of deep rigor and practical business context.'),
  ('senior', 'data_analyst', 2, 70, 'A high-end competence multiplier for disciplined agencies.'),
  ('senior', 'campaign_manager', 2, 70, 'Premium senior manager who keeps pace high and chaos contained.'),
  ('senior', 'campaign_manager', 2, 70, 'Strong at navigating tradeoffs without hidden execution debt.'),
  ('senior', 'campaign_manager', 2, 70, 'Reliable orchestrator for time-critical campaign pivots.'),
  ('senior', 'campaign_manager', 2, 70, 'Maintains cross-team trust while driving hard delivery timelines.'),
  ('senior', 'campaign_manager', 2, 70, 'A high-value leader for complex campaign operations.'),

  ('senior', 'sales_representative', 3, 75, 'Top-tier senior seller with elite audience reading and execution timing.'),
  ('senior', 'sales_representative', 3, 75, 'Can create large reach outcomes while keeping strategy intact.'),
  ('senior', 'sales_representative', 3, 75, 'Adept at high-stakes visibility plays in unstable attention climates.'),
  ('senior', 'sales_representative', 3, 75, 'Delivers scale, discipline, and credible narrative pressure control.'),
  ('senior', 'sales_representative', 3, 75, 'A marquee hire for agencies aiming to dominate reach.'),
  ('senior', 'data_analyst', 3, 75, 'Elite senior analyst with consistently high-confidence recommendations.'),
  ('senior', 'data_analyst', 3, 75, 'Finds hidden risk vectors before they become expensive surprises.'),
  ('senior', 'data_analyst', 3, 75, 'Transforms complex data ecosystems into clear strategic direction.'),
  ('senior', 'data_analyst', 3, 75, 'Exceptional at protecting campaign credibility through evidence discipline.'),
  ('senior', 'data_analyst', 3, 75, 'A marquee competence hire for precision-focused firms.'),
  ('senior', 'campaign_manager', 3, 75, 'Elite operator who keeps ambitious campaigns coherent end to end.'),
  ('senior', 'campaign_manager', 3, 75, 'Excellent at coordinating pivots without losing delivery confidence.'),
  ('senior', 'campaign_manager', 3, 75, 'Strong leadership presence with practical crisis execution instincts.'),
  ('senior', 'campaign_manager', 3, 75, 'Can run multi-layer campaign programs with minimal friction.'),
  ('senior', 'campaign_manager', 3, 75, 'A marquee coordination hire for high-ambition agencies.'),

  ('senior', 'sales_representative', 4, 80, 'Premier senior reach driver with polished strategic restraint.'),
  ('senior', 'sales_representative', 4, 80, 'Brings high-output visibility growth with fewer self-inflicted setbacks.'),
  ('senior', 'sales_representative', 4, 80, 'Masterful at timing amplification for maximum narrative impact.'),
  ('senior', 'sales_representative', 4, 80, 'Consistently converts attention spikes into campaign-level advantage.'),
  ('senior', 'sales_representative', 4, 80, 'A flagship hire for firms targeting mainstream dominance.'),
  ('senior', 'data_analyst', 4, 80, 'Premier analyst with exceptional strategic foresight and rigor.'),
  ('senior', 'data_analyst', 4, 80, 'Builds unusually reliable decision frameworks in chaotic environments.'),
  ('senior', 'data_analyst', 4, 80, 'Frequently identifies hidden instability before public exposure.'),
  ('senior', 'data_analyst', 4, 80, 'Delivers high-precision insight that upgrades every campaign layer.'),
  ('senior', 'data_analyst', 4, 80, 'A flagship competence hire for elite execution plans.'),
  ('senior', 'campaign_manager', 4, 80, 'Premier campaign leader with rare execution clarity under pressure.'),
  ('senior', 'campaign_manager', 4, 80, 'Can align strategy and delivery at scale without process drag.'),
  ('senior', 'campaign_manager', 4, 80, 'Prevents high-cost failures through proactive orchestration discipline.'),
  ('senior', 'campaign_manager', 4, 80, 'Runs difficult campaign portfolios with calm, reliable control.'),
  ('senior', 'campaign_manager', 4, 80, 'A flagship management hire for advanced agency operations.'),

  ('senior', 'sales_representative', 5, 85, 'Top-band senior with rare reach instincts and disciplined narrative control.'),
  ('senior', 'sales_representative', 5, 85, 'An elite visibility specialist built for high-stakes public contests.'),
  ('senior', 'sales_representative', 5, 85, 'Combines scale, timing, and message hygiene at a premium level.'),
  ('senior', 'sales_representative', 5, 85, 'Frequently defines the campaign ceiling for reach-heavy agencies.'),
  ('senior', 'sales_representative', 5, 85, 'A top-market hire when visibility outcomes are mission-critical.'),
  ('senior', 'data_analyst', 5, 85, 'Top-band analyst with elite judgment in noisy, adversarial contexts.'),
  ('senior', 'data_analyst', 5, 85, 'Sets the standard for evidence quality and strategic signal clarity.'),
  ('senior', 'data_analyst', 5, 85, 'Can reshape campaign direction with a single high-confidence read.'),
  ('senior', 'data_analyst', 5, 85, 'An elite competence anchor for agencies chasing long-term credibility.'),
  ('senior', 'data_analyst', 5, 85, 'A top-market analytical hire with clear high-impact upside.'),
  ('senior', 'campaign_manager', 5, 85, 'Top-band campaign lead with elite coordination and delivery discipline.'),
  ('senior', 'campaign_manager', 5, 85, 'Holds complex portfolios together while improving strategic execution quality.'),
  ('senior', 'campaign_manager', 5, 85, 'An elite operator for agencies managing sustained high-pressure cycles.'),
  ('senior', 'campaign_manager', 5, 85, 'Turns ambitious plans into consistent outcomes across teams.'),
  ('senior', 'campaign_manager', 5, 85, 'A top-market leadership hire for advanced campaign orchestration.')
on conflict do nothing;
